### ISSUE TITLE
No provision for header values as parameters on the request.

### ISSUE THREAD

**Issue by easygoingalex** [abelsilva/swaggerwcf#1]
Hi there,

I obtained your Swagger tool via NuGet, and managed to get it producing documentation as expected. However, I require all operations on my API to send a token in the header parameters. In addition to this is the requirement to send OAuth parameters in the headers too, however, I cannot see how to express this to your attributes.

From what I can see, it seems like its not implemented, however if it is, please could you tell me how to do it.

Many Thanks,
Alex

**Comment by abelsilva** [comment]
Hi Alex

It is not implemented.

I suppose it will need specific tags for auth and headers and then parse them to insert the data in swagger json.
