### ISSUE TITLE
Not found error on accessing api docs

### ISSUE THREAD

**Issue by Dia6lo** [abelsilva/swaggerwcf#10]
I've completed your getting started steps and I'm getting 404 error when I try to access %address%/api-docs.
What am I doing wrong?

**Comment by abelsilva** [comment]
I don't know, paste here the relevant parts of the configuration

**Comment by J4S0Nc** [comment]
I had to add this in my web.config: 

  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true"/>
  </system.webServer>

**Comment by J4S0Nc** [comment]
```
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true"/>
  </system.webServer>
```

**Comment by Dia6lo** [comment]
Oh, it seems that I've missed your reply e-mail, @abelsilva. Sorry for such delay :/
I've moved to Web API, so I can't recall relevant parts of configuration.
