### ISSUE TITLE
different api-docs on routing

### ISSUE THREAD

**Issue by JFDionne** [abelsilva/swaggerwcf#100]
I wonder if it's possible to untag SwaggerWcfHidden with routing, my goal is to have different api-docs depending on which url they are asking.

I tried to pass a string of visibleTag on the Servicebuilder.Build by adding a new constructor of SwaggerWcfEndpoint, but I don't know if it's possible to add a argument to it by using

`RouteTable.Routes.Add(new ServiceRoute("api-docs", new WebServiceHostFactory(), typeof(SwaggerWcfEndpoint("MyServiceNameTag"))));`

**Comment by JFDionne** [comment]
@abelsilva it is acceptable or not? :)

**Comment by abelsilva** [comment]
let me know if you are able to do it with the latest version

**Comment by abelsilva** [comment]
closing
