### ISSUE TITLE
[Question] How to serve only the swagger.json file?

### ISSUE THREAD

**Issue by pouladpld** [abelsilva/swaggerwcf#102]
I'm trying to use generated `swagger.json` only without enabling directory browse. Is it supported? If yes, how?

**Comment by abelsilva** [comment]
check latest release, let me know if you still have any issues

you can disable with 
```
SwaggerWcfEndpoint.DisableSwaggerUI = true;
```

(check sample project: `Global.asax.cs`)

**Comment by pouladpld** [comment]
Works fine. Thank you.
