### ISSUE TITLE
Enum with VB something wrong

### ISSUE THREAD

**Issue by JFDionne** [abelsilva/swaggerwcf#106]
Hi, something wrong with the enum, because I'm using vb?

Inline Model 1 {
  Est_Accroche (string, optional) = ['Non', 'Oui', 'EnDirection']
}

seem to be in string, but when I do the request, I got the number, like 1, 2 or 3.

**Comment by abelsilva** [comment]
it's more an issue in .NET and WCF as you can see if you search about it

in `C#` the same issue applies (you can check the sample service), you will see everything in strings, but the post has to be in numbers

**Comment by JFDionne** [comment]
Hi, but since we need to post it in number, maybe the inline model should do something like:
Inline Model 1 {
Est_Accroche (integer, optional) = [0: 'Non', 1: 'Oui', 2: 'EnDirection']
}

Or something like that?

**Comment by abelsilva** [comment]
an enum in swagger spec can be described as
```
              "enum": [
                "clueless",
                "lazy",
                "adventurous",
                "aggressive"
              ]
```

I don't have any to create a mapping

only thing I could do is force to map as int

or you can put that info in the descriptions (descriptions support markdown)

**Comment by JFDionne** [comment]
Oh, you don't "build yourself" the comment of the Inline model?

**Comment by abelsilva** [comment]
no, it's built from the json file and the json file has to follow swagger spec rules

**Comment by JFDionne** [comment]
I cheat on function itself, I did a 
<SwaggerWcfReturnType(GetType(enumType))>

and I put a return of string of this function, so I got it "perfect" doc:
string = ['OK', 'Refuse', 'Non_Autorise']

Is there a way for doing the same but with a property/vars ?

I do a convertion to my enum when I receive the string. but at least the dev know what need to be send to the endpoint.

**Comment by abelsilva** [comment]
not seeing a simple way to do it

**Comment by abelsilva** [comment]
converting all `enums` to numbers, if needed, the conversion can be placed in the description fields

**Comment by JFDionne** [comment]
Hi, how do you use it?

**Comment by abelsilva** [comment]
you can see the example for parameters on models
if you are returning an enum directly on the function, you can set the functions descriptions


I don't believe you have any way to set it up dynamically

**Comment by JFDionne** [comment]
Okay, thank.

Too bad we can't do it at runtime, need to think to modify the description if we add 1.

**Comment by abelsilva** [comment]
can't see any way to do it, attributes can't have any dynamic fields, everything must be available at compile time

**Comment by JFDionne** [comment]
Hi @abelsilva, what do you think about this [code](https://github.com/JFDionne/swaggerwcf/commit/ae27810a08777d6e0dd59ba8c28eed2b16d0a4d8)

that give something like this into the model:
![image](https://user-images.githubusercontent.com/1706002/34137429-e814516a-e438-11e7-8913-44ac9d0d132a.png)

No need to modify the text each time we add a value into the enum
