### ISSUE TITLE
List<string> as parameter is invalid in swagger.json

### ISSUE THREAD

**Issue by colbroth** [abelsilva/swaggerwcf#111]
This issue is similiar to issue #105 except that List<string> is a parameter instead of the return value.

I added the following to the IStore.cs file

`        [WebInvoke()]
        [OperationContract]
        void CreateBookTest(List<string> bookIds); `

The swagger.json file produced by swaggerwcf has an error. The editor.swagger.io reports "Could not resolve reference: #/definitions/System.String" and there are several other errors also.

` {"operationId":"SwaggerWcf.Test.Service.BookStore.CreateBookTest",
"consumes":["application/json"],
"produces":["application/json"],
"parameters":[
{"name":"bookId","in":"body","required":true,
"schema":{
"type":"array"},
"items":{"schema":{"$ref":"#/definitions/System.String"}},
"collectionFormat":0}], `

Expected:

` {"operationId":"SwaggerWcf.Test.Service.BookStore.CreateBookTest",
"consumes":["application/json"],
"produces":["application/json"],
"parameters":[
{"name":"bookIds","in":"body","required":true,
"schema":
{"type":"array"},
"items":{ "type":"string" }], `

Note: I removed the collectionFormat and changed the the schema

**Comment by abelsilva** [comment]
can you try latest version?

**Comment by colbroth** [comment]
I tried with version 0.2.1

**Comment by abelsilva** [comment]
`0.2.2` is latest version

**Comment by colbroth** [comment]
This is now fixed in version 0.2.2
