### ISSUE TITLE
Enum should be query parameter

### ISSUE THREAD

**Issue by colbroth** [abelsilva/swaggerwcf#112]
This issue is similiar to #104 but for an enum query parameter.

I added the following to the IStore.cs file

`        
  [OperationContract]
  [WebInvokeAttribute(Method = "GET")]
  int BookTest(BookTypeEnum first, int second);
`

And to the Book.cs file

`    public enum BookTypeEnum : byte
    {
        one = 1,
        two = 2
    }
`

For this declaration, first and second should be query parameters. SwaggerWcf is treating first as a request body parameter and second as a query parameter.
The swagger.json file has the following:

`
"/v1/rest/BookTest":{
"get":{"operationId":"SwaggerWcf.Test.Service.BookStore.BookTest",
"consumes":["application/json","application/xml"],"produces":["application/json","application/xml"],
"parameters":[{
"name":"first",
"in":"body",
"required":true,
"schema":{"$ref":"#/definitions/SwaggerWcf.Test.Service.Data.BookTypeEnum"}},{"name":"second","in":"query","required":true,"type":"integer","format":"int32"}],
`

Expected:

`
"/v1/rest/BookTest":{
"get":{"operationId":"SwaggerWcf.Test.Service.BookStore.BookTest",
"consumes":["application/json","application/xml"],"produces":["application/json","application/xml"],
"parameters":[{
"name":"first",
"in":"query",
"required":true,
"type": "array",
 "collectionFormat": "pipes",
 "items": {
              "type": "string",
              "enum": [
                "one",
                "two"
              ]
   }
{"name":"second","in":"query","required":true,"type":"integer","format":"int32"}],
`

or anchors may be used for example:

definitions:
  Origin:
    type: string
    description: Campaign origin
    enum: &origin
      - one
      - two

paths:
  /BookTest:
    get:
      parameters:
        - in: query
          name: status
          description: Origin
          required: false
          type: array
          collectionFormat: pipes
          items:
            type: string
            enum: *origin

**Comment by abelsilva** [comment]
can you try latest version?

**Comment by colbroth** [comment]
I tried with version 0.2.1

**Comment by abelsilva** [comment]
`0.2.2` is latest version

**Comment by colbroth** [comment]
This is now fixed in version 0.2.2
