### ISSUE TITLE
DateTime should be query parameter

### ISSUE THREAD

**Issue by colbroth** [abelsilva/swaggerwcf#116]
In version 0.2.4, DateTime is put in body and should be a query parameter.

I added the following to the IStore.cs file

`        [OperationContract]
        [WebInvoke(Method = "GET")]
        void BookTest(DateTime startTime, DateTime endTime);
`

For this declaration, startTime and endTime should be query parameters. SwaggerWcf is treating them as  request body parameters.

The swagger.json file has the following:

`
"/v1/rest/BookTest":
{
"get":{
"operationId":"SwaggerWcf.Test.Service.BookStore.BookTest",
"consumes":["application/json","application/xml"],
"produces":["application/json","application/xml"],
"parameters":[
{"name":"startTime","in":"body","required":true,
"schema":{
"$ref":"#/definitions/System.DateTime"}},
{"name":"endTime",
"in":"body","required":true,
"schema":{"$ref":"#/definitions/System.DateTime"}}],
"responses":{"default":{"description":"not available"}}}},
`

Expected:

`
"/v1/rest/BookTest": {
      "get": {
        "operationId": "SwaggerWcf.Test.Service.BookStore.BookTest",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/json",
          "application/xml"
        ],
        "parameters": [
          {
            "name": "startTime",
            "in": "query",
            "required": true,
            "type": "string",
            "format": "date-time"
          },
          {
            "name": "endTime",
            "in": "query",
            "required": true,
            "type": "string",
            "format": "date-time"
          }
        ],
        "responses": {
          "default": {
            "description": "not available"
          }
        }
      }
    },
`

The change I made was to set "in" to "query", "type" to string, "format" to "date-time"

**Comment by colbroth** [comment]
This also happens with type "byte". 
[OperationContract] [WebInvoke(Method = "GET")] void BookTest(byte value);
swagger puts in body but expected it as a query parameter with type: string and format: byte

**Comment by abelsilva** [comment]
can you check if it works now?

**Comment by abelsilva** [comment]
check with `0.2.6`, now any type represented as string will be used in query (except if the type is a `Stream`)

**Comment by colbroth** [comment]
Fixed in version 0.2.6. Thank you
