### ISSUE TITLE
 Invalid generated schema object in new version

### ISSUE THREAD

**Issue by pouladpld** [abelsilva/swaggerwcf#118]
Generated parameter(_Schema Object_) in `swagger.json` for object types is wrong.

> Followings are representations of `paths.['/my-route'].post.parameters[0].schema` object.

> The same bug possibly exists for the arrays of complex object types.

## Actual

```json
{
    "schema": {
        "properties": {
            "my_prop": {
                "type": "string",
                "uniqueItems": false
            }
        },
        "type": "object",
        "format": "my_object_request_type"
    }
}
```

## Expected

```json
{
    "schema": {
        "$ref": "#/definitions/my_object_request_type"
    }
}
```

## Version
`0.2.7` (just upgraded from `0.2.4`)

**Comment by pouladpld** [comment]
Actually, I can't confirm at what version this went wrong but these recent versions produce totally invalid swagger file.

**Comment by abelsilva** [comment]
can you show me the function signature?

**Comment by pouladpld** [comment]
I can't reproduce it anymore. I believe it was just my own mistake in copying some parts of the json.
