### ISSUE TITLE
AutoRest Code Generator compatibility

### ISSUE THREAD

**Issue by tdjastrzebski** [abelsilva/swaggerwcf#12]
Hi,

suggest to make sure generated swagger can be used as VS "REST API Client" generator installed as add-in with Azure SDK.
https://github.com/Azure/autorest/
preferably the initial version 0.9.6, since this one is still being distributed with Azure SDK although the tool is not Azure dependent/specific.

It looks like there are some compatibility issues, MS "AutoRest Code Generator" does not produce any output based on swagger output from your tool.

Output from MS recommended swagger tools https://github.com/domaindrivendev/Swashbuckle seems to be ok. However, is Web API tool, not WCF.
See: https://azure.microsoft.com/en-us/blog/announcing-the-azure-sdk-2-7-for-net/
"Positive Impacts of Template Swagger Tweaks for Client Developers" section.

Kind regards,

Tomasz

![3d61edd8-0a17-11e6-8c40-25e842b3681d](https://cloud.githubusercontent.com/assets/7325277/14815209/4d78b3ac-0baa-11e6-8882-2797ef44af3d.png)

**Comment by tdjastrzebski** [comment]
An update: the latest Autorest version is 0.15.0
It is enough to just install it for the UI tool to use it.
PM>  Install-Package AutoRest

**Comment by abelsilva** [comment]
don't know if I'll commit much time with this.

when I try to generate I get an error saying complex types need a Byte[] parameter

```
error: [FATAL] Error generating client model: Please specify a field with type of System.Byte[] to deserialize the file contents to
```

this happens at:
```
Microsoft.Rest.Modeler.Swagger.OperationBuilder.VerifyFirstPropertyIsByteArray(CompositeType serviceType)
```

The comparison is:
```
responseType.Properties.FirstOrDefault(p => p.Type is PrimaryType && ((PrimaryType)p.Type).Type == KnownPrimaryType.ByteArray);
```

Even if I add a byte[] property to a complex class, that comparison doesn't work, as the type ends up as:
```
responseType.Properties[0].Type	{IList<ByteArray>}
```

If you want to help on this you're welcome

**Comment by abelsilva** [comment]
won't implement support for now

**Comment by nedumarans** [comment]
Is this issue fixed? we are getting the error error: [FATAL] Error generating client model: Please specify a field with type of System.Byte[] to deserialize the file contents to when we have an API does file upload. is there workaround for this?
