### ISSUE TITLE
Enums not working properly

### ISSUE THREAD

**Issue by wnilsson** [abelsilva/swaggerwcf#123]
Hi, 

It looks like there's an issue with enums as these appear as member name strings instead of integers i.e. for the below enum, the example value is "StartsWith" instead of 0. The model value is better as it shows all the enum names however it shows the property as type string when should be type integer... 

Also, it doesn't show the corresponding values needed to make the call but perhaps this is swagger standard?

    [DataContract]
    [Serializable]
    public enum SearchType
    {
        [EnumMember]
        StartWith = 0,
        [EnumMember]
        Contains = 1
    }

**Comment by abelsilva** [comment]
I'll push a new version today

**Comment by wnilsson** [comment]
Thanks!

**Comment by wnilsson** [comment]
Hi again, I can see that the enums are now showing the raw int values which is good however the property data type is still showing as string when it should be int i.e.

![image](https://user-images.githubusercontent.com/33943578/33534235-5756a770-d8fa-11e7-9475-ca7ac3944477.png)

Could this please be changes to integer?


Cheers
