### ISSUE TITLE
Request Model Data Type Info Does Not Wrap

### ISSUE THREAD

**Issue by wnilsson** [abelsilva/swaggerwcf#124]
Hi, the information text for model data type is not wrapping in the HTML page so  it cuts off i.e.
![image](https://user-images.githubusercontent.com/33943578/33297526-98f7bc7e-d435-11e7-8518-7d57deaa22a0.png)

FYI I'm using Chrome.

Cheers

**Comment by abelsilva** [comment]
this is not a bug on SwaggerWcf, it's an issue on swagger-ui

create an issue on their project
https://github.com/swagger-api/swagger-ui

you can always set your model name with attributes

**Comment by wnilsson** [comment]
Hi,

I Can see other Swagger UI web apps with the request model html wrapping properly so are you sure this issue should be raised against the UI? 

How will changing the model name stop the property description text from not wrapping?

Cheers

**Comment by abelsilva** [comment]
I'm using `swagger-ui` `2.2.10`, which is the latest in `2.X` series

Everything HTML/CSS/JS is from `swagger-ui`, the only output you can see from SwaggerWcf is the `swagger.json` file
