### ISSUE TITLE
Init replacing service.Info 

### ISSUE THREAD

**Issue by maxanse** [abelsilva/swaggerwcf#125]
https://github.com/abelsilva/swaggerwcf/blob/753ab97746a1c875ca0e5a7a9add3ec9f7532a23/src/SwaggerWcf/SwaggerWcfEndpoint.cs#L59

Perhaps I have overlooked something, but when using the parameterless ctor this ends up in _null_ for `service.Info`, which was set in `buildService` a line before.

**Comment by abelsilva** [comment]
i'll release a new version soon
