### ISSUE TITLE
Swagger UI Content Disappears after App Pool Recycle

### ISSUE THREAD

**Issue by wnilsson** [abelsilva/swaggerwcf#126]
Hi, I have configured my WCF IIS web app by adding:

RouteTable.Routes.Add(new ServiceRoute("swagger", new WebServiceHostFactory(), typeof(SwaggerWcfEndpoint))); 

to the Global.asmx Application_Start method as per the instructions and after the initial call, all looks good however after the default 20 min app pool recycle, all the dynamic API content disappears and all that's visible is the info. 

If I break on Application_Start, the RouteTable code is executed once again but no API's can be seen until I re publish the entire app once again i.e. refresh the DLL's...

Please help.

**Comment by abelsilva** [comment]
I can't replicate this

After recycle, SwaggerWcf restarts normally and regenerates the content without any issue

**Comment by wnilsson** [comment]
Hi, 

This always occurs for my local dev (win 10) and win server 2012 environments whenever the app pool is recycled and the only way I can get it to work is to change the IIS settings to never recycle...

As mentioned, I can break on the Application_Start code and it is definitely being hit after the recycle therefore the SwaggerWcf code is being re-executed, however the information does not show until a new publish is done.

Please find attached the before and after screen shots and Global.asax.cs and Web.configs:

![beforerecycle](https://user-images.githubusercontent.com/33943578/33532160-4d07ef54-d8eb-11e7-85b0-b9b71e0c58c0.PNG)
![afterrecycle](https://user-images.githubusercontent.com/33943578/33532161-4f6979e8-d8eb-11e7-8cbb-1ad2ab65406f.PNG)
[Global.asax.txt](https://github.com/abelsilva/swaggerwcf/files/1525366/Global.asax.txt)
[Web.config.txt](https://github.com/abelsilva/swaggerwcf/files/1525367/Web.config.txt)



Cheers

**Comment by abelsilva** [comment]
show me the `swagger.json` contents of both states

I'd say if swagger is showing the UI, it is working correctly, it may probably be unable to find your libraries

**Comment by wnilsson** [comment]
[SwaggerBeforeIISReset.json.txt](https://github.com/abelsilva/swaggerwcf/files/1529281/SwaggerBeforeIISReset.json.txt)

[SwaggerAfterIISReset.json.txt](https://github.com/abelsilva/swaggerwcf/files/1529283/SwaggerAfterIISReset.json.txt)

**Comment by abelsilva** [comment]
something wrong on the files

the first one is not the raw file from swaggerwcf, the paths are not contained in strings
the second one has a different title, version and description!

**Comment by abelsilva** [comment]
I just saw your Global.asax
The first time you start you are loading the second option because you can find the assembly
The second time you can't find the assembly

So, why after a refresh, would your currentdomain assemblies change?
What are you doing to make that happen?
Your issue seems to be the handling of assemblies, not anything related to swaggerwcf

**Comment by wnilsson** [comment]
They are the same app and I have changed nothing - all I did was an app pool recycle - the bin folder wasn't touched and all the required assemblies are all there ... 

The name, title & version changed because I have code in the Global.asax file to dynamically change these based on the availability of a specific assembly. This particular assembly and all the others decorated with SwaggerWcf attributes are not being reloaded after recycle.

Perhaps this is an IIS issue...

**Comment by abelsilva** [comment]
but the title/version/description change because the assemblies information change

I can't understand how after a recycle, the function `GetFactFindAssemblyVersion()` would return a different value
Are you adding/removing `dll` files from the folder?

**Comment by wnilsson** [comment]
Nope - I'm not touching anything in the bin folder... 

It doesn't appear to be a SwaggerWcf issue - maybe assembly caching  or something?

**Comment by abelsilva** [comment]
try to log all assemblies that start with `Coin`

```
AppDomain.CurrentDomain.GetAssemblies().Where(a => a.FullName.StartsWith("Coin")).Select(a => a.FullName)
```

**Comment by wnilsson** [comment]
I checked the output from AppDomain.CurrentDomain.GetAssemblies() and most of the Coin. assemblies are not present so the AppDomain has changed post app pool recycle... Looks like on first publish, all assemblies are in the app domain but recycling changes this and assemblies are only loaded when needed i.e. lazy loading...

**Comment by abelsilva** [comment]
where are you adding the routes to your APIs?
I only see the one for `swaggerwcf`

**Comment by wnilsson** [comment]
The API's are dynamically loaded using service activation i.e.

<serviceHostingEnvironment aspNetCompatibilityEnabled="true" multipleSiteBindingsEnabled="true">
  <serviceActivations>
    <add relativeAddress="CoinModules/Shared/AuthenticationService.svc" factory="Coin.WCFService.Common.ServiceFactor.....

etc

**Comment by abelsilva** [comment]
but where to setup the route?

**Comment by wnilsson** [comment]
![image](https://user-images.githubusercontent.com/33943578/33587099-a6a52f38-d9c0-11e7-9d5c-2210645483a5.png)

**Comment by abelsilva** [comment]
hum... never used it

**Comment by abelsilva** [comment]
IIS has configurations on the app pool to auto-start or alwaysrun, maybe that could help?

**Comment by wnilsson** [comment]
Perhaps this is whats going on i.e. using service activation means all dll's are available at first publish but after IIS reset or recycle, the cache is flushed and assemblies are only loaded on demand thereafter...

Anyway, I'm happy for this to be closed or deferred - if no one else is complaining, we're prob the only ones using service activation... 

I'll simply  change IIS to never recycle - seems this is recommended these days anyway...

Cheers

**Comment by abelsilva** [comment]
alright, although you could always kind of `force` it
You can do an HTTP GET on the APIs URLs to force IIS to load them

closing the issue...
