### ISSUE TITLE
Enum data type showing string

### ISSUE THREAD

**Issue by wnilsson** [abelsilva/swaggerwcf#128]
Hi again, I can see that the enums are now showing the raw int values which is good however the property data type is still showing as string when it should be int i.e.

![image](https://user-images.githubusercontent.com/33943578/33534909-83581a76-d8fe-11e7-947e-5a76a8781fa9.png)

Could this be changed to integer please?

Cheers

**Comment by abelsilva** [comment]
should be available in a few minutes
https://www.nuget.org/packages/SwaggerWcf/0.2.9

**Comment by pouladpld** [comment]
LOL. I can't believe this really happened!!! :rofl: 

Once @wnilsson asks why his enum values are not shown as integers, _all the enums_ got converted to integer values in v0.2.9. :disappointed:

**Comment by JFDionne** [comment]
@pouladpld but since enum string doesn't work in .NET it's more "normal" to have them in int, no?

I made a modification for we can see the value of the enum in the swagger: [https://github.com/JFDionne/swaggerwcf/commit/ae27810a08777d6e0dd59ba8c28eed2b16d0a4d8](url)
