### ISSUE TITLE
Support multiple levels of complex types

### ISSUE THREAD

**Issue by JonasSyrstad** [abelsilva/swaggerwcf#13]
a datacontract like this does not reflect the items collection:
`
public class ClientListResponse : ResponseBase<ClientList>
    {
    }
`

`public class ResponseBase<T>
    {
        [DataMember]
        public T Body { get; set; }
    }
 public class ClientList
    {
        [DataMember]
        public List<ClientSummary> Clients { get; set; }
    }
`
The mapping helper adds the definition to the definitionsTypesList, but when these are built any complex type inside is not mapped.

**Comment by abelsilva** [comment]
can you retry with latest version? 1.0.7 

Did some changes that might impact this

**Comment by JonasSyrstad** [comment]
Hi,
A lot better. However, when using IEnumerable<T> the T type is not refelcted. Works for List<T>.

**Comment by abelsilva** [comment]
can you retry again? 1.0.8

**Comment by abelsilva** [comment]
let me know if you still have any issue
