### ISSUE TITLE
JSON referecnse object doesn't need to have any property other than $ref

### ISSUE THREAD

**Issue by pouladpld** [abelsilva/swaggerwcf#132]
A reference doesn't need to have any other property defined in that object.

For example, see generated `swagger.definitions.['SwaggerWcf.Test.Service.Data.Book'].properties` object.

#### Expected

```json
"Author": {
  "$ref": "#/definitions/SwaggerWcf.Test.Service.Data.Author"
}
```

#### Actual

```json
"Author": {
  "description": "Book Author",
  "$ref": "#/definitions/SwaggerWcf.Test.Service.Data.Author"
}
```

**Comment by abelsilva** [comment]
check 0.2.10 if it is working as expected
