### ISSUE TITLE
SwaggerWcfParameter Required does not work

### ISSUE THREAD

**Issue by davidrybar** [abelsilva/swaggerwcf#134]
using [SwaggerWcfParameter(Required = false)] on method parameter does not change required value to false in generated json

**Comment by HolisticDeveloper** [comment]
+1

**Comment by HolisticDeveloper** [comment]
It appears that you have to provide a default value for the parameter in your method signature; otherwise it is deemed to be required.

**Comment by abelsilva** [comment]
Yes, without a default value WCF forces the parameter as required

Swagger JSON must describe correctly the WCF endpoint
