### ISSUE TITLE
Fields within return classes are not exported to the .json file

### ISSUE THREAD

**Issue by rmurfster** [abelsilva/swaggerwcf#136]
Using your SwaggerWcf.Test.Service, I modified the Book class to the following:

    [DataContract]
    [Description("Book with title, first publish date, author and language")]
    [SwaggerWcfDefinition(ExternalDocsUrl = "http://en.wikipedia.org/wiki/Book", ExternalDocsDescription = "Description of a book")]
    public class Book
    {
        ...

        [DataMember]
        public Book2 book2 { get; set; }

        [DataMember]
        public Book3 book3 { get; set; }
    }

    public class Book2
    {
        public Int32 thisDosentWork;

        public Int32 thisWorks { get; set; }
    }

    public struct Book3
    {
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 129)]
        public String thisDoesntWork;

        public String thisWorks { get; set; }
    }

Only the properties and not the fields are exported to the .json file.  Now, you may say the answer is, “Well, then just make your fields properties”, but alas, I can’t as my structures (ie; Book3) are passed to an unmanaged dll, which requires passing in fixed size strings (as in my example) and not properties.

Any way you can make SwaggerWcf support fields?

Thanks!

Richard

**Comment by davidrybar** [comment]
Same for me....
David

**Comment by abelsilva** [comment]
check 0.2.10 if it is working as expected (including the fields in swagger)

**Comment by davidrybar** [comment]
Fields are working as expected now, thanks!

**Comment by davidrybar** [comment]
Unfortunately for me, starting from 0.2.10 the generated json changed the way we can not upgrade. We use several svc and the annotation [SwaggerWcf("/ServiceX.svc")] stopped working as expected. We always get first svc as basePath and those SwaggerWcf("...") in every service get ignored :/

**Comment by abelsilva** [comment]
I see, you have multiple SwaggerWcf definitions with different paths, right?

I'll take a look at it later today.
I'll prevent using the SwaggerWcf annotation value as basePath if we have multiple values.
In that case, the previous behaviour will be used.

**Comment by davidrybar** [comment]
Yes, that is it. Thanks for a help.

**Comment by abelsilva** [comment]
can you check if it all working now ? tks

**Comment by abelsilva** [comment]
release `0.2.13`
https://www.nuget.org/packages/SwaggerWcf/0.2.13

**Comment by davidrybar** [comment]
Both works as expected in version 0.2.13
Thanks!
