### ISSUE TITLE
Add Security to SwaggerWCF

### ISSUE THREAD

**Issue by gacostab** [abelsilva/swaggerwcf#14]
Hi Abel, 

Thanks for your library very useful. I have a question I need to add security to the initial call in swagger. Something like this. 

![image](https://cloud.githubusercontent.com/assets/19768984/16137160/0de3926e-3474-11e6-9cce-c28b03802eee.png)

I don't know, if it is possible with your package?
Kind regards, 

Juan

**Comment by abelsilva** [comment]
Hi Juan

Can't be done, maybe you add security through IIS.

Thanks
Abel

**Comment by gabrielacosta** [comment]
I will a security using Oauth with Wcf. I supposed it was not possible. Thanks anyway.
