### ISSUE TITLE
SwaggerWcfResponse varying examples

### ISSUE THREAD

**Issue by jonathh21** [abelsilva/swaggerwcf#151]
I am trying to figure out how to provide different examples to different response examples.

I have a happy day http status code ok working but I also have bad request and unauthorized defined but their examples are the same as the happy day one which is misleading.

Any help warmly received thanks!

**Comment by abelsilva** [comment]
you can check the `Store.svc.cs` for details

sample:
```
[SwaggerWcfResponse(HttpStatusCode.BadRequest,
                            "Bad request",
                            true,
                            ExampleMimeType = "application/json",
                            ExampleContent = "{\"error:\": \"error description\"}")]
```

**Comment by abelsilva** [comment]
please note this will not show up on the swagger UI, for some reason it doesn't show

if you copy to the editor (https://editor2.swagger.io/) and do a 'Paste JSON' it will show the multiple examples

the JSON contains the examples
