### ISSUE TITLE
Need more info on SwaggerWcf attribute

### ISSUE THREAD

**Issue by junrau** [abelsilva/swaggerwcf#154]
I have SwaggerWcf set up on my WCF service.

The services's URL is "https://localhost:8031/ApiService.svc".
The service's REST endpoint is "https://localhost:8031/ApiService.svc/rest".
The route for Swagger is "doc", so the URL for Swagger is "https://localhost:8031/doc.".

The Swagger UI loads.

The I add the SwaggerWcf attribute.  The SwaggerWcf home page, in step 6, says, "Add the SwaggerWcf and AspNetCompatibilityRequirements attributes to the class providing the base path for the service (the same as used in step 2)."  On this same page, step 2 uses "api-docs" and step 6 uses "/v1/rest".  I don't know what to put in the attribute parameter, and no matter what I use returns a 400 error.  Can you give me some guidance on what I need to use in the SwaggerWcf attribute on my service class?

Thanks.

**Comment by abelsilva** [comment]
"api-docs" and "/v1/rest" are different things

* `api-docs` is the documentation endpoint
* `/v1/rest` is *your* endpoint
