### ISSUE TITLE
Disable 'Try it out'

### ISSUE THREAD

**Issue by jonathh21** [abelsilva/swaggerwcf#156]
We are rolling out our SWAGGER documentation and it and this package are fricken awesome..

However we have some challenges around support the 'Try it out' so we'd like to disable it for now.

How can this be done?

Thank you.

**Comment by abelsilva** [comment]
I mean, it does have `supportedSubmitMethods` but it doesn't seem to work as a query parameter

it would force me to change the source code of swagger-ui
