### ISSUE TITLE
failed to parse JSON/YAML response

### ISSUE THREAD

**Issue by github-rajk** [abelsilva/swaggerwcf#157]
I have integrated Swagger to a simple WCF component

I Looked into the similar issue https://github.com/abelsilva/swaggerwcf/issues/114 but looks like mine is different

Please look into this and help me in fixing the issue

What is the best way to debug i am unable to find any Json file to see the json it is trying to parse

somehow markdown is not working for xml so attached the config file

Service Project (WCFSample)

**Service Interface**

`   
    public interface IService1
    {
        [SwaggerWcfPath("Get Data", "Gets Data")]
        [WebInvoke(UriTemplate = "/data",
            BodyStyle = WebMessageBodyStyle.Bare,
            Method = "Get",
            RequestFormat = WebMessageFormat.Json,
            ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        string GetData(int value);

        [SwaggerWcfPath("Get Data", "Gets Data using data contract")]
        [WebInvoke(UriTemplate = "/datawithcontract",
            BodyStyle = WebMessageBodyStyle.Bare,
            Method = "Get",
            RequestFormat = WebMessageFormat.Json,
            ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        CompositeType GetDataUsingDataContract(CompositeType composite);

        // TODO: Add your service operations here
    }

    // Use a data contract as illustrated in the sample below to add composite types to service operations.
    // You can add XSD files into the project. After building the project, you can directly use the data types defined there, with the namespace "WcfSample.ContractType".
    [DataContract(Name = "CompositeType")]
    [Description("Composite Type")]
    [SwaggerWcfDefinition(ExternalDocsDescription = "Composite Type")]
    public class CompositeType
    {
        bool boolValue = true;
        string stringValue = "Hello ";

        [DataMember(Name = "boolVal")]
        [Description("Boolean Value")]
        public bool BoolValue
        {
            get { return boolValue; }
            set { boolValue = value; }
        }

        
        [DataMember(Name = "stringVal")]
        [Description("String Value")]
        public string StringValue
        {
            get { return stringValue; }
            set { stringValue = value; }
        }
    }
`

**Service Class**
` 
public class Service1 : IService1
    {
        [SwaggerWcfTag("Sample")]
        [SwaggerWcfResponse(HttpStatusCode.Created, "Get Data, value in the response body with id updated")]
        [SwaggerWcfResponse(HttpStatusCode.BadRequest, "Bad request", true)]
        [SwaggerWcfResponse(HttpStatusCode.InternalServerError,
            "Internal error (error)", true)]
        public string GetData(int value)
        {
            return string.Format("You entered: {0}", value);
        }

        [SwaggerWcfTag("Sample")]
        [SwaggerWcfResponse(HttpStatusCode.Created, "Get Data using data contract")]
        [SwaggerWcfResponse(HttpStatusCode.BadRequest, "Bad request", true)]
        [SwaggerWcfResponse(HttpStatusCode.InternalServerError,
            "Internal error (error2)", true)]
        public CompositeType GetDataUsingDataContract(CompositeType composite)
        {
            if (composite == null)
            {
                throw new ArgumentNullException("composite");
            }
            if (composite.BoolValue)
            {
                composite.StringValue += "Suffix";
            }
            return composite;
        }
    }
`

**Host Project ( WCFSwaggerHost)**

**App.Config**

<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="swaggerwcf" type="SwaggerWcf.Configuration.SwaggerWcfSection, SwaggerWcf" />
  </configSections>
  <swaggerwcf>
    <tags>
      <tag name="LowPerformance" visible="false" />
    </tags>
    <settings>
      <setting name="InfoDescription" value="Sample Service to test SwaggerWCF" />
      <setting name="InfoVersion" value="0.0.1" />
      <setting name="InfoTermsOfService" value="Terms of Service" />
      <setting name="InfoTitle" value="SampleService" />
      <setting name="InfoContactName" value="Abel Silva" />
      <setting name="InfoContactUrl" value="http://github.com/abelsilva" />
      <setting name="InfoContactEmail" value="no@e.mail" />
      <setting name="InfoLicenseUrl" value="https://github.com/abelsilva/SwaggerWCF/blob/master/LICENSE" />
      <setting name="InfoLicenseName" value="Apache License" />
    </settings>
  </swaggerwcf>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
    </startup>
  <system.serviceModel>
    <services>
      <service name="WcfSample.Service1">
        <endpoint address="http://0.0.0.0:8090/" binding="webHttpBinding" contract="WcfSample.IService1" />
      </service>
      <service name="SwaggerWcf.SwaggerWcfEndpoint">
        <endpoint address="http://localhost/docs" binding="webHttpBinding" contract="SwaggerWcf.ISwaggerWcfEndpoint" />
      </service>
    </services>
    <behaviors>
      <endpointBehaviors>
        <behavior>
          <webHttp automaticFormatSelectionEnabled="true" />
        </behavior>
      </endpointBehaviors>
      
    </behaviors>
  </system.serviceModel>
</configuration>

[app.config.txt] (https://github.com/abelsilva/swaggerwcf/files/1980969/app.config.txt)

**Startup class**

` class Program
    {
        static void Main(string[] args)
        {
            using (var host = new ServiceHost(typeof(Service1)))
            {
                host.Open();
                var swaggerHost = new ServiceHost(typeof(SwaggerWcfEndpoint));
                swaggerHost.Open();
                Console.WriteLine("Press Enter to stop");
                Console.ReadLine();
            }
        }
    } `

**Comment by envy666** [comment]
<endpoint address="http://localhost/docs" binding="webHttpBinding" contract="SwaggerWcf.ISwaggerWcfEndpoint" />

this config  try to use host> baseaddress 
not address
