### ISSUE TITLE
Swagger not working in WindowsService

### ISSUE THREAD

**Issue by 13ANS13** [abelsilva/swaggerwcf#159]
In WindowsService:::
       When opening in browser:
       request: http://localhost:8092/docs
       response: failed to parse JSON/YAML response

in WebService:::
     success

Please give an example with windowsService Give me.

**Comment by abelsilva** [comment]
why are you asking for an example?

the README explains how to configure SwaggerWcf in self-hosted mode, that would be the same as setting up as a service

**Comment by nazari-ali** [comment]
tanks, it`s worked,
I had another question: 
how using enum parameter in header
and how I will add description & default value to parameter

my sample:

[SwaggerWcfPath("get new application release", "return application release")]
        [OperationContract]
        [WebInvoke(UriTemplate = "/get/new", Method = "POST", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json, BodyStyle = WebMessageBodyStyle.WrappedRequest)]
        ApplicationRelease GetApplicationNewRelease([SwaggerWcfParameter(Required = true, Description = "username Id")]string userId);

It does not work
Thanks for helping me
