### ISSUE TITLE
Can not Scan the Service!

### ISSUE THREAD

**Issue by eclipsexml** [abelsilva/swaggerwcf#163]
when I config my WCF Service in Self Hosted, I get the respose "failed to parse JSON/YAML response"。

**Comment by eclipsexml** [comment]
I started my wcf Service via code ServiceHost.. not by app.config . but the config of webswaggerhost is in app.config

**Comment by eclipsexml** [comment]
this is my code, just a default wcf service lib and a console

Console:
 static void Main(string[] args)
        {
            Uri baseurl = new Uri("http://127.0.0.1:8082/Service1");
            ServiceHost sh = new ServiceHost(typeof(Service1), baseurl);
            ContractDescription cd = ContractDescription.GetContract(typeof(IService1).UnderlyingSystemType);
            cd.Name = "Service1";
            EndpointAddress ea = new EndpointAddress(baseurl);
            ServiceEndpoint se = new ServiceEndpoint(cd, GetWSHttpBinding(), ea);
            var sdb= sh.Description.Behaviors.Find<ServiceDebugBehavior>();
            if (sdb == null)
            {
                sdb = new ServiceDebugBehavior();
                sh.Description.Behaviors.Add(sdb);
            }
         
            sdb.IncludeExceptionDetailInFaults = true;
            var smb = sh.Description.Behaviors.Find<ServiceMetadataBehavior>();
            if(smb == null)
            {
                smb = new ServiceMetadataBehavior();
                sh.Description.Behaviors.Add(smb);
            }
            smb.HttpGetEnabled = true;
            smb.HttpGetUrl = baseurl;

            sh.AddServiceEndpoint(se);
            sh.Open();
            if(sh.State == CommunicationState.Opened)
            {
                Console.WriteLine("Service Started!");
            }
            var swaggerHost = new WebServiceHost(typeof(SwaggerWcfEndpoint));
            SwaggerWcfEndpoint.FilterVisibleTags = FilterVisibleTags;
            SwaggerWcfEndpoint.FilterHiddenTags = FilterHiddenTags;
            SwaggerWcfEndpoint.DisableSwaggerUI = false;

            swaggerHost.Open();
            if(swaggerHost.State == CommunicationState.Opened)
            {
                Console.WriteLine("Swagger Service Started!");
            }
            Console.ReadLine();
        }

        private static List<string> FilterVisibleTags(string path, List<string> visibleTags)
        {
            return visibleTags;
        }

        private static List<string> FilterHiddenTags(string path, List<string> hiddenTags)
        {
            return hiddenTags;
        }

Contract:
[ServiceContract]
    public interface IService1
    {
        [SwaggerWcfPath("GetData", "test Get Data")]
        [WebInvoke(
        BodyStyle = WebMessageBodyStyle.Bare,
        Method = "POST",
        RequestFormat = WebMessageFormat.Json,
        ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        string GetData(int value);

        [OperationContract]
        CompositeType GetDataUsingDataContract(CompositeType composite);

        // TODO: 在此添加您的服务操作
    }

    // 使用下面示例中说明的数据约定将复合类型添加到服务操作。
    // 可以将 XSD 文件添加到项目中。在生成项目后，可以通过命名空间“TesetService.ContractType”直接使用其中定义的数据类型。
    [DataContract]
    public class CompositeType
    {
        bool boolValue = true;
        string stringValue = "Hello ";

        [DataMember]
        public bool BoolValue
        {
            get { return boolValue; }
            set { boolValue = value; }
        }

        [DataMember]
        public string StringValue
        {
            get { return stringValue; }
            set { stringValue = value; }
        }
    }

Service:
 [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
    [SwaggerWcf]
    public class Service1 : IService1
    {
        [SwaggerWcfTag("Books")]
        public string GetData(int value)
        {
            return string.Format("You entered: {0}", value);
        }

        public CompositeType GetDataUsingDataContract(CompositeType composite)
        {
            if (composite == null)
            {
                throw new ArgumentNullException("composite");
            }
            if (composite.BoolValue)
            {
                composite.StringValue += "Suffix";
            }
            return composite;
        }
    }

I think these SwaggerAttributes work well enough,but not,What else do I need to configure?

**Comment by eclipsexml** [comment]
I just want to test the method "getdata", I hope you can answer my question，thanks

**Comment by eclipsexml** [comment]
OK,I Solve the problem by myself and your source code。

**Comment by abelsilva** [comment]
closing since it was solved

**Comment by wojiaofsp** [comment]
兄弟你咋解决的啊
