### ISSUE TITLE
Define base URL

### ISSUE THREAD

**Issue by ssochacki** [abelsilva/swaggerwcf#17]
Hi, and thanks for this great work !

I was just wondering if there was a way to define the base URL of the project.
For instance, I've deployed my service on http://localhost/API/ but the docs considers it was deployed to http://localhost.

Thank you.

Stéphane S.

**Comment by abelsilva** [comment]
Hi

Can you post here your commands for configuration of RouteTables?

```
RouteTable.Routes.Add([...])
```

**Comment by ssochacki** [comment]
Here's a sample :
`RouteTable.Routes.Add(new ServiceRoute("docs", new WebServiceHostFactory(), typeof(SwaggerWcf.SwaggerWcfEndpoint)));`
`RouteTable.Routes.Add(new ServiceRoute("entities", new WebServiceHostFactory(), typeof(UNFP.Webservice.Service.Entity)));`
`...`
`RouteTable.Routes.Add(new ServiceRoute("appattributes", new WebServiceHostFactory(), typeof(UNFP.Webservice.Service.App)));`

**Comment by abelsilva** [comment]
Where do you see the error?

if you open 
http://<host>:<port>/API/docs

do you get the page? and the error is the swagger.json location?

**Comment by ssochacki** [comment]
Hi Abel,
I'm sorry, I wasn't clear enough about my problem.

Actually, the documentation works just fine.
But thing is, my webservice is deployed at the address http://myserver/API/, but the documentation considers it was deployed on http://myserver (without even the last slash, which makes the doc pointing out to routes like http://myservermyroute instead of http://myserver/API/myroute).

At the end of the documentation page, I can see "BASE URL:" whereas I was waiting for something like "BASE URL: http://myserver/API/").

Hence, my question was, is there any way to force the base URL onto to something else ?

**Comment by abelsilva** [comment]
Hi

Ok, got it now.
Check step 6 of docs, if you change 
```
[SwaggerWcf("/v1/rest")]
```

to the value you want, does it work?

**Comment by abelsilva** [comment]
I guess it worked.

Feel free to reopen if you need more help

**Comment by ssochacki** [comment]
Hi,
And sorry for the late anwser, last weeks were pretty busy at work.

Actually, I already figured out I could solve my problem by using [SwaggerWcf(...)].
However, I thought there were a general command to define the API root once for the whole project, that's why I asked.

It works now the way I need though, thank you for your answer.
