### ISSUE TITLE
HTTP 404 error

### ISSUE THREAD

**Issue by Giuggio** [abelsilva/swaggerwcf#18]
Hello,

I've implemented SwaggerWcf in my project but I cannot solve a HTTP 404 file not found issue when opening http://localhost:58564/api-docs/index.html?url=http://localhost:58564/api-docs/swagger.json.
Is there a way to debug the issue? Thanks!

**Comment by abelsilva** [comment]
You can check for IIS errors.

Please also review the steps described for configuration

**Comment by Giuggio** [comment]
Thanks, it's true. <modules runAllManagedModulesForAllRequests="true"/> is the cause and solution
