### ISSUE TITLE
Required authorizations [Question]

### ISSUE THREAD

**Issue by JFDionne** [abelsilva/swaggerwcf#19]
Hi, is there a way for adding the required authorizations to be included in the Swagger JSON?

Like BasicAuth

**Comment by abelsilva** [comment]
Hi

Swagger spec allows the specification of security
http://swagger.io/specification/#swaggerObject

```
securityDefinitions
security
```

Currently, SwaggerWcf does not support adding this information.

**Comment by abelsilva** [comment]
closing as this is not on development plans
