### ISSUE TITLE
Models  NameSpaces.Class but I want just CLass

### ISSUE THREAD

**Issue by auriou** [abelsilva/swaggerwcf#195]
Is it possible, that the name of the models is just the name of their class and not the namespace + class
Examples =  Company.Entities.Business.Catalog.Sale  but I want juste Sale

**Comment by justin0522** [comment]
add attribute on the model class like this
[SwaggerWcfDefinition(ModelName = "Sale")]

**Comment by auriou** [comment]
I can not add this attribute to my class because I am in a project POCO use by other projects and I do not want dependencies to third-party libraries

https://github.com/auriou/swaggerwcf

I fork your project to make changes on OperationsId and Models name and enums.

The enums were not fully compatible with the swagger standard, and I added the x-ms-enum attribute for generate enums by autorest

**Comment by justin0522** [comment]
great !
please refer to 
https://github.com/microsoft/OpenAPI.NET/tree/master/src/Microsoft.OpenApi/Models
for your new question
