### ISSUE TITLE
Adding BasePath to the swaggerwcf/settings section in the Web.config prepends the base path to an already full url

### ISSUE THREAD

**Issue by easygoingalex** [abelsilva/swaggerwcf#2]
Hi there,

I'm not sure why, but if you omit the base path property, the swagger stuff formulates the call with the full URL (I can't see where to stop this from happening.) So when you add the BasePath property, it is being prepended to an already absolute URI (certainly for the test harness which fails when you try to invoke an operation.)

Kind Regards,
Alex

**Comment by abelsilva** [comment]
Hi Alex

I'll need to check.

When you say 'omit the base path property', are you referring to `[SwaggerWcf("/v1/rest")]` ?
