### ISSUE TITLE
Double/decimal value (vb.net)

### ISSUE THREAD

**Issue by JFDionne** [abelsilva/swaggerwcf#20]
Hi, double or decimal value appear in Model of "Data Type" as a "number", but doesn't appear in "Model Schema".

Working with integer

**Comment by abelsilva** [comment]
Hi

From my understanding:

http://swagger.io/specification/
says double and float are defined as 'number'
decimal is not specified.

Swagger is not a .net spec, so it maps generically to integer/number.

Let me know what you think

Thanks
Abel

**Comment by abelsilva** [comment]
closing because double/decimal are supposed to be declared as number

**Comment by JFDionne** [comment]
it's declared as number, but the problem is they don't appear into the Model Schema. Check the attach file.
![untitled_ta](https://cloud.githubusercontent.com/assets/1706002/16569681/179012ba-4207-11e6-8e83-2e177d43f566.png)
![Uploading Untitled_ta.png…]()
