### ISSUE TITLE
Lists are not processed properly

### ISSUE THREAD

**Issue by andriibratanin** [abelsilva/swaggerwcf#21]
Swagger v0.1.10 from Nuget fails to generate "swagger.json" file in case if an operation contract's parameter is of list type and parameter's name cannot be found in an uri template.

Actually, I am not sure if it is right to check the presence of every parameter name in the uri at all because some request methods can take parameter's contents from body (for example, "POST").

I've created a separate repository with a solution to reproduce the issue: https://github.com/andriibratanin/SwaggerWcfBug

**Comment by abelsilva** [comment]
Hi

Can you check with V0.1.11? (just pushed it)

**Comment by andriibratanin** [comment]
Now it is working. Thank you very much

**Comment by abelsilva** [comment]
nice! thanks
