### ISSUE TITLE
Please sign with a strong name key

### ISSUE THREAD

**Issue by PhlashGBG** [abelsilva/swaggerwcf#23]
Hi Abel, I'm interested in using SwaggerWcf for a commercial project, where we sign all our assemblies as part of a larger security scheme that we wouldn't wish to remove. At this time I am unable to even try SwaggerWcf out as I cannot build it into the project. Please consider signing the NuGet packaged assemblies (no need to expose your signing keys in the source tree) so people in my position are at least able to test ideas out :)

Many thanks,
Phil.

**Comment by abelsilva** [comment]
Hi Phil

I won't be signing assemblies.
If you really need them signed it should be very straightforward for you to clone the project and sign them with in your own build environment.

Thanks
Abel

**Comment by PhlashGBG** [comment]
OK, would have been nice to use NuGet but I'll go down the route of building locally. Thanks for the prompt response.
