### ISSUE TITLE
Double/decimal value don't appear into the Model Schema

### ISSUE THREAD

**Issue by JFDionne** [abelsilva/swaggerwcf#25]
Hi, I don't know how to "reopen" a ticket, so I'll create a new one:

Hi, double or decimal value appear in Model of "Data Type" as a "number", but doesn't appear in "Model Schema".

Check the attach screen capture, see the longitude and latitude:
![179012ba-4207-11e6-8e83-2e177d43f5660](https://cloud.githubusercontent.com/assets/1706002/16791211/ac325d40-488a-11e6-858f-7eadaa72a76c.png)

**Comment by abelsilva** [comment]
Where are you using the long/lat? In a function? class?
Can you share the function/class signature?

**Comment by JFDionne** [comment]
sure, this is the class
<DataContract()>
Public Class clsGeo
    Private _longitude As Double
    Private _latitude As Double
    Private _derniere_mise_a_jour As String

    <DataMember()>
    Public Property longitude As Double
        Get
            Return _longitude
        End Get
        Set(value As Double)
            _longitude = value
        End Set
    End Property

    <DataMember()>
    Public Property latitude As Double
        Get
            Return _latitude
        End Get
        Set(value As Double)
            _latitude = value
        End Set
    End Property

    <DataMember()>
    Public Property derniere_mise_a_jour As String
        Get
            Return _derniere_mise_a_jour
        End Get
        Set(value As String)
            _derniere_mise_a_jour = value
        End Set
    End Property
End Class

**Comment by abelsilva** [comment]
Hi JFDionne 

This is an issue with swagger UI
Later I'll release an update to SwaggerWcf with an updated dist of Swagger UI

Thanks
Abel

**Comment by abelsilva** [comment]
updated SwaggerWcf to 0.1.12 with new dist of Swagger UI

can you check if it fixes this issue?

Thanks
Abel

**Comment by JFDionne** [comment]
working! thank :)

**Comment by abelsilva** [comment]
glad to know
