### ISSUE TITLE
Incorrect InType when parameter name is part of the query

### ISSUE THREAD

**Issue by rgonzalezVW** [abelsilva/swaggerwcf#32]
Consider the following example function:
```
        [OperationContract]
        [WebInvoke(UriTemplate = "patients/check", BodyStyle = WebMessageBodyStyle.Bare, RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        Patient ApiCheckPatient(Patient patient);
```
As you can see "patient" is not a parameter in the Uri, but the text "patient" is partially contained, and, since Mapper.GetInType only checks the parameter name, is wrongly marked as "InType.Path".
Please, consider adding braces "{}" when searching the Uri for parameter placeholders.

**Comment by abelsilva** [comment]
thanks, good catch

**Comment by abelsilva** [comment]
new package released with fix
