### ISSUE TITLE
Tag description does not appear on the Swagger UI

### ISSUE THREAD

**Issue by akgaurav** [abelsilva/swaggerwcf#34]
![capture](https://cloud.githubusercontent.com/assets/11269081/18634515/cfe24148-7e9e-11e6-90e3-6114f01b8494.PNG)

I am able to see description "Everything about your pets" from the sample url provided next to user : 
But unable to see the same for my service MySrv1 and MySrv2. 

Please help

**Comment by abelsilva** [comment]
hard to help without any source showing your configuration

**Comment by abelsilva** [comment]
feel free to reopen with more details
