### ISSUE TITLE
Array types mapping

### ISSUE THREAD

**Issue by TimSylvester** [abelsilva/swaggerwcf#37]
The types contained in a collection aren't mapped the same way as property types.  For example, when a string property is processed, it's displayed as simply "string" but when a collection of strings is encountered, it's shown as "System.String", and that is unnecessarily listed as an inline type.

![image](https://cloud.githubusercontent.com/assets/1383447/18682108/d35cb4e4-7f1f-11e6-97c5-4030649aa2b7.png)

Ideally, IMO, this would read "Segments ([string]):" (i.e., JS array notation) or, to be more explicit, "Segments (Array[string]):"

I'm not immediately sure how to improve this, though.  I was thinking that `DefinitionsBuilder.ProcessProperties` should be calling `Helpers.MapSwaggerType` instead of using the type directly (`prop.Items.Ref = t.FullName`), but that's going to require passing around the definitions list in several more places.  I tinkered with it, but ended up with "Inline Type 1" instead.

**Comment by abelsilva** [comment]
I'm not seeing a way to do this right now

I'll have to review it

**Comment by abelsilva** [comment]
I think this should be fixed now for native types

**Comment by TimSylvester** [comment]
Awesome, thanks again!
