### ISSUE TITLE
BuildSchema fails with List return type

### ISSUE THREAD

**Issue by sm-g** [abelsilva/swaggerwcf#4]
`BuildSchema` has line `Type t = type.GetElementType();` which results to null when type is generic List. Can be fixed with [http://stackoverflow.com/a/7072121/3009578](http://stackoverflow.com/a/7072121/3009578)

**Comment by abelsilva** [comment]
fixed with the solution provided, new version was published in nuget, it should be available in a moment after indexing

thanks
