### ISSUE TITLE
No provision for header values as parameters on the request. SwaggerWcf

### ISSUE THREAD

**Issue by senthilsethu** [abelsilva/swaggerwcf#41]
Hi Team,

I have implemented SwaggerWcf in my WCF service project via NuGet. It works. I need to send access token for my services in header parameters. But I don't know how to achieve this. Could you please help me on this?

If you can provide any working sample it will be appreciated. Many thanks.

Kind Regards
Senthil

**Comment by abelsilva** [comment]
It's currently not supported in SwaggerWcf

Probably in a future release

**Comment by jinojose83** [comment]
I also facing the same issue, Need to send access token in headers. Is there any other workaround for this?

**Comment by abelsilva** [comment]
I'm working on it, in a few days should be implemented

**Comment by jinojose83** [comment]
Thank You...

**Comment by abelsilva** [comment]
You can test this now, add to your functions:
```
[SwaggerWcfHeader(name: "clientId", required:false, description: "Client ID", defaultValue: "000")]
```

**Comment by senthilsethu** [comment]
It works fine. Thank you very much. Appreciate your help.
