### ISSUE TITLE
Does this library support headers?

### ISSUE THREAD

**Issue by apstory** [abelsilva/swaggerwcf#42]
Is it possible to document, for example, the Apikey parameter being passed through in the header:
parameters:
        - name: Apikey
          in: header
          description: API key
          required: false
          type: string
          format: string
          default: xxxx

**Comment by abelsilva** [comment]
Not currently, is there any details in swagger specs ?

**Comment by apstory** [comment]
yes the example above shows how to define it:

in: header

**Comment by abelsilva** [comment]
You can test this now, add to your functions:
```
[SwaggerWcfHeader(name: "clientId", required:false, description: "Client ID", defaultValue: "000")]
```

**Comment by apstory** [comment]
Thanks for looking into this, it's adding the header twice now though...

**Comment by abelsilva** [comment]
can't replicate issue, anyway, I added a filter to remove duplicates from headers list

please check if issue still happens

**Comment by abelsilva** [comment]
assuming it's fixed... please reopen if you have any issue
