### ISSUE TITLE
change /swagger.json UriTemplate or allow it to be configurable

### ISSUE THREAD

**Issue by amelialaundy** [abelsilva/swaggerwcf#43]
Hey Abel, 
I came across your implementation of Swagger for WCF and have managed to get it working on our solution (we have a handrolled solution for documentation at the moment and need to move towards swagger).

The only issue I came across is that the SwaggerWcfEndpoint implementation uses “/swagger.json” as the UriTemplate and I finally realised that this was what was causing the swagger output to be inaccessible in our API. 
As soon as I got your code running inside our solution and could debug through it I changed the URL to “/swagger” and it worked perfectly. (we actually can't access the UI component hosted at the other endpoint in ISwaggerWcfEndpoint.cs but don't need to use it so it's not causing an issue).

I believe this is down to how WCF routing can pick up specific urls or ignore others, I did find an article that semi explained it but I seem to have lost it.

So I’m just wondering whether this is something you would consider either changing (/swagger.json) or to allow it to be configurable by the user ( happy to try and solve this and do a PR)?

**Comment by amelialaundy** [comment]
ok so we have managed to  figure out that we can use `/swagger` and leave the SwaggerWcfEndpoint value as `/swagger.json`, it seems to work just fine if we don't use .json in the URL when trying to hit the endpoint.

But we have found another problem which is when response/request objects inherit from List<string> the list within the array in the swagger definition is System.string which is invalid swagger:

`MyList: {
type: "array",
items: {
$ref: "#/definitions/System.String"
},
uniqueItems: false
}`

**Comment by abelsilva** [comment]
glad you resolved, the last issue you mentioned is an already open issue: #37
