### ISSUE TITLE
SwaggerWcfTag hidefromspec seem to don't work

### ISSUE THREAD

**Issue by JFDionne** [abelsilva/swaggerwcf#44]
Hi,

the hidefromspeec on the SwaggerWcfTag seem to don't work.

I use it on my public interface like: (vb.net)

```
<SwaggerWcfTag("Test_Tag", True)>
<SwaggerWcfPath("Function small desc", "function full desc")>
<WebInvoke(Method:="GET", RequestFormat:=WebMessageFormat.Json, ResponseFormat:=WebMessageFormat.Json, UriTemplate:="/test/{id}")>
<OperationContract>
Function Test_function(id As Long) As boolean
```

the function still appear on my list, but if I put 
    <tags>
      <tag name="Test_Tag" visible="false" />
    </tags>

on my web.config it's disappear.

thank you for all your work! very nice projet

**Comment by abelsilva** [comment]
Hi

The parameter ```hideFromSpec``` on ```SwaggerWcfTag``` is used to hide the tag itself, not the function.
You can see it in the description:

![image](https://cloud.githubusercontent.com/assets/1167088/19728854/5cc0284e-9b6b-11e6-94e0-ffca12377435.png)

Thanks

**Comment by JFDionne** [comment]
Ah, but if you don't want to see tag why you put the tag? :)

Can I change this Issue for make a suggestion to add a param for hide the tag and the function, like if we set the visible = false on the config file?
<tag name="TAG_Name" visible="false" />

The point is to have all the tag visible false by default and enable only the tag I want into this endpoint.

**Comment by abelsilva** [comment]
the idea is when you use the tag to hide the functions, e.g., 'functionToHide'
You probably don't want that tag to show up in the spec, it is only for internal management

but if you want to hide a function you can use
```[SwaggerWcfHidden]```

**Comment by JFDionne** [comment]
okay, if I add [SwaggerWcfHidden] it will but the "visible" = false?
Do it will appear if I put tag name="Function_Tag" visible="true" into the web.config ?

**Comment by abelsilva** [comment]
I didn't get the question

the 
```
[SwaggerWcfHidden]
```
will hide the function

if with the tag you ask to be visible, one of the actions will override the other

**Comment by JFDionne** [comment]
Sorry i'm not clear :)

I have 4 endpoint on the same projet, since we can't "choose" which projet I want to show up on the api-docs I use the 
[tag name="Test_1_Tag" visible="true"] 
[tag name="Test_2_Tag" visible="false"] 
[tag name="Test_3_Tag" visible="false"] 
[tag name="Test_4_Tag" visible="false"] 
into the web.config.

and I put 
<SwaggerWcfTag("Test_1_Tag")> on my code for each fonction of the endpoint, I'll use _2 _3 and _4 on the other.

My point here is, do we have a way for having the visible false by default so I can put only visible=true on the endpoint I want to see on the api-docs?

right now if I add another endpoint, I'll need to go on each web,config and add the visible=false for this projet.

**Comment by abelsilva** [comment]
Yes, you would need, by default it should true (like it is now)

I guess it would be ok to add a new parameter to the ```SwaggerWcfHidden``` to help on the cases you mentioned, to change the value of ```visible```

**Comment by JFDionne** [comment]
it will be wonderful!

**Comment by abelsilva** [comment]
The idea is that you mark your methods with 
```
SwaggerWcfHidden
```
and one SwaggerTag, e.g.:
```
SwaggerWcfTag("show")
```

If then, when you want to show them, just add to ```web.config```:
```
<tag name="show" visible="true"/>
```
The ```web.config``` configuration will override the ```SwaggerWcfHidden``` tag

**Comment by abelsilva** [comment]
please let me know if it works for you, thanks!

**Comment by JFDionne** [comment]
Working, thank you ! :)

**Comment by JFDionne** [comment]
oups, I talked too fast, not working for me with version 18, I'll open a new ticket

**Comment by abelsilva** [comment]
As I said, one of the actions will override the other, and as we can see now, ```SwaggerWcfHidden``` will have more priority

If you control from the web.config you don't need to use ```SwaggerWcfHidden```

**Comment by abelsilva** [comment]
Sorry, it should work yes, let me check

**Comment by JFDionne** [comment]
Oh, but the use of SwaggerWcfHidden was not to be able to "force" to show it from the web.config?

**Comment by abelsilva** [comment]
Should work like I last described, something is probably wrong

The idea is that you mark your methods with 

```
SwaggerWcfHidden
```

and one SwaggerTag, e.g.:

```
SwaggerWcfTag("show")
```

If then, when you want to show them, just add to `web.config`:

```
<tag name="show" visible="true"/>
```

The `web.config` configuration will override the `SwaggerWcfHidden` tag
