### ISSUE TITLE
Host and Schemes attributes missing

### ISSUE THREAD

**Issue by KiranChauhan91** [abelsilva/swaggerwcf#45]
Hello,

When you try swagger.json file with Microsoft Power Apps, it throws validation message for Host missing. I did fixed that in the code but you may want to apply that in the main branch.

Regards,
Kiran Chauhan

**Comment by abelsilva** [comment]
Hi Kiran

Are you able to send a PR?
Or can you show the changes or more details about the error?

Thanks
