### ISSUE TITLE
Unused definitions generated for primitive types

### ISSUE THREAD

**Issue by peekyou** [abelsilva/swaggerwcf#47]
Hello,

I have a method in my service that returns a long. In the YAML generated there is a definition for this type:
```
System.Int64:
    type: integer
    format: int64
```

But it is unused in the response of the operation:
```
responses:
     '200':
        description: Ok
        schema:
            type: integer
            format: int64
```

This causes a warning. How could I avoid this ?
Thank you

**Comment by abelsilva** [comment]
I don't understand the issue you're having

What YAML generated? SwaggerWCF generates a JSON file

And where do you see the warning?

**Comment by peekyou** [comment]
Sorry if it was unclear.
Let's take a simple example. I have a WCF service with one method GetInteger, returning an int.
Here the JSON generated:
```
{
   "swagger":"2.0",
   "info":{
      "version":"0.0.1",
      "title":"Systems Service"
   },
   "paths":{
      "/systems":{
         "get":{
            "operationId":"GetAllSystems",
            "consumes":[
               "application/json"
            ],
            "produces":[
               "application/json"
            ],
            "responses":{
               "default":{
                  "description":"not available",
                  "schema":{
                     "type":"integer",
                     "format":"int32"
                  }
               }
            }
         }
      }
   },
   "definitions":{
      "System.Int32":{
         "type":"integer",
         "format":"int32"
      }
   }
}
```

We can see that, there is a definition created for the type integer, but that definition is not used in the response schema. Either there should be a $ref, or the definition for primitives types should be removed.

And the warning appears when I try to validate this JSON: http://editor.swagger.io

**Comment by abelsilva** [comment]
got it! just pushed a new version that should fix this

thanks

**Comment by peekyou** [comment]
Thank you !
