### ISSUE TITLE
path argument with default value wrongly interpreted as aparameter type body

### ISSUE THREAD

**Issue by stojy** [abelsilva/swaggerwcf#48]
WCF supports defining optional path variables (i.e. path variable with an optional argument), however this appears to be incorrectly interpreted as a 'body' parameter type instead of an optional 'path' parameter type.  Also, the generated URL is incorrect.

MSDN refrence.. https://msdn.microsoft.com/en-us/library/bb675245(v=vs.110).aspx

Example..
```
        [WebGet(UriTemplate = "/race/{raceKey}/silks/{acceptorKey=null}?width={width}&height={height}", ResponseFormat = WebMessageFormat.Json)]
        Task<Stream> GetRaceSilks(string raceKey, string acceptorKey = null, string width = null, string height = null);
```

![capture](https://cloud.githubusercontent.com/assets/11408611/20129826/a98d959e-a68d-11e6-9259-0072b9d1f708.PNG)

Issues marked in red..
1.  wrong parameter type.  should be type=path and string
2. wrong generated url.  should be http://localhost:30295/racing/race/1/silks?width=3&height=4 or http://localhost:30295/racing/race/1/silks/null?width=3&height=4

**Comment by abelsilva** [comment]
added some changes to make sure parameter shows with correct type

I decided to remove the default value from the URL as I don't see from the swagger spec how to do it

let me know your thoughts on this

**Comment by abelsilva** [comment]
assuming it's fixed... please reopen if you have any issue
