### ISSUE TITLE
Not able to work with https

### ISSUE THREAD

**Issue by rkrans** [abelsilva/swaggerwcf#49]
I've been trying to create a swagger https endpoint on my wcf service with no success.  Chrome allows me to navigate to the URI and enter credentials but shows an empty page.  I can create an http endpoint with no issues, but as soon as I attempt to go https I get an empty page.  I have a main https endpoint on port 8129 and am trying to get a swagger endpoint on port 8131 - i'm guess my config file isn't quite right.  Any suggestions would be appreciated, my app.config is roughly:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="swaggerwcf" type="SwaggerWcf.Configuration.SwaggerWcfSection, SwaggerWcf" />
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  
  </configSections>
  <swaggerwcf>
    <tags>
      <tag name="LowPerformance" visible="false" />
    </tags>
    <settings>
      <setting name="InfoDescription" value="REST service." />
      <setting name="InfoVersion" value="0.0.1" />
      <setting name="InfoTermsOfService" value="Terms of Service" />
      <setting name="InfoTitle" value="xxx" />
      <setting name="InfoContactName" value="bob" />
      <setting name="InfoContactUrl" value="http://xxx.com" />
      <setting name="InfoContactEmail" value="support@xxx.com" />
      <setting name="InfoLicenseUrl" value="https://github.com/abelsilva/SwaggerWCF/blob/master/LICENSE" />
      <setting name="InfoLicenseName" value="Apache License" />
      
      
    </settings>
  </swaggerwcf>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
  </startup>
  <system.serviceModel>
    <serviceHostingEnvironment aspNetCompatibilityEnabled="true" multipleSiteBindingsEnabled="true" />
    <bindings>
      <basicHttpBinding>
        <binding name="MyServiceBinding" maxBufferSize="2147483647" maxBufferPoolSize="0" maxReceivedMessageSize="2147483647" messageEncoding="Mtom" transferMode="Streamed">
          <readerQuotas maxArrayLength="2147483647" maxBytesPerRead="2147483647" maxDepth="2147483647" maxNameTableCharCount="2147483647" maxStringContentLength="2147483647" />
          <security mode="TransportWithMessageCredential">
            <transport clientCredentialType="None" />
            <message clientCredentialType="UserName" />
          </security>
        </binding>
      </basicHttpBinding>
      <webHttpBinding>
        <binding name="FileManagerBinding" transferMode="Streamed" maxReceivedMessageSize="2147483647" crossDomainScriptAccessEnabled="false">
          <readerQuotas maxArrayLength="2147483647" maxStringContentLength="2147483647" />
          <security mode="Transport">        
            <transport clientCredentialType="Basic"></transport>
          </security>
        </binding>
      </webHttpBinding>
    </bindings>
    <services>
      <service behaviorConfiguration="ServerServiceBehavior" name="Wti.Enterprise.Server.EnterpriseService">
        <endpoint address="TestTracker" behaviorConfiguration="MyEndpointBehavior" binding="basicHttpBinding" bindingConfiguration="MyServiceBinding" name="EnterpriseService" contract="Wti.Enterprise.Server.IEnterpriseService" />
        <endpoint address="FileServer" binding="webHttpBinding" contract="Wti.Enterprise.Server.IFileManagerService" behaviorConfiguration="web" bindingConfiguration="FileManagerBinding"></endpoint>
        <endpoint address="REST" binding="webHttpBinding" contract="Wti.Enterprise.Server.ISecureRESTSvc" behaviorConfiguration="web2" bindingConfiguration="FileManagerBinding"></endpoint>
        <endpoint address="mex" binding="mexHttpsBinding" name="MexHttpsBindingEndpoint" contract="IMetadataExchange" />
        <host>
          <baseAddresses>
            <add baseAddress="https://localhost:8129/Wti.TestTracker.Server" />
          </baseAddresses>
        </host>
      </service>
       
    <service name="SwaggerWcf.SwaggerWcfEndpoint">
        <endpoint address="docs" binding="webHttpBinding" contract="SwaggerWcf.ISwaggerWcfEndpoint"
                  behaviorConfiguration="swagger" bindingConfiguration="FileManagerBinding"/>
      <host>
        <baseAddresses>
          <add baseAddress="https://mycomputer:8131"/>
        </baseAddresses>
      </host>
      </service>
    </services>
    <behaviors>
      <serviceBehaviors>
        <behavior name="ServerServiceBehavior">
          <serviceMetadata httpsGetEnabled="true" httpGetEnabled="true" httpsGetUrl="" />
          <serviceDebug includeExceptionDetailInFaults="true" />
          
          <serviceCredentials>
            <userNameAuthentication userNamePasswordValidationMode="Custom" customUserNamePasswordValidatorType="Wti.Enterprise.Server.UserAuthentication,Wti.Enterprise.Server" />
            
          </serviceCredentials>
          <serviceAuthorization principalPermissionMode="Custom">
            <authorizationPolicies>
              <add policyType="Wti.Enterprise.Server.AuthorizationPolicy,Wti.Enterprise.Server" />
            </authorizationPolicies>
          </serviceAuthorization>
        </behavior>
      </serviceBehaviors>
      <endpointBehaviors>
        <behavior name="MyEndpointBehavior">
          
        </behavior>
        <behavior name="web">
          <webHttp />
        </behavior>
        <behavior name="web2">
          <webHttp />
        </behavior>
        <behavior name="swagger">
          <webHttp automaticFormatSelectionEnabled="true" />
        </behavior>
      </endpointBehaviors>
    </behaviors>
  </system.serviceModel>

**Comment by abelsilva** [comment]
if you remove swaggerwcf from your project, are you able to open your own WCF service using HTTPS?

**Comment by abelsilva** [comment]
closing, please reopen if issue still exists
