### ISSUE TITLE
minor issues

### ISSUE THREAD

**Issue by tdjastrzebski** [abelsilva/swaggerwcf#5]
Hi, I just tried to use your service component.

Three issues I discovered so far:
1. Swagger file has no content if WebGet/WebInvoke attributes are placed on the implementing methods, rather than interface. I know it is not recommended, but it is permissible.
2. Code fails with "null reference exception" when WebInvoke attrib has no Method argument - POST is the default value.
3. Even swagger content is internally properly built no file gets returned. GetSwaggerFile() method completes but browser gets stacked displaying "fetching resource list: http://localhost:63780/api-docs/swagger.json". In my case the content is just ~ 9k.

Best regards,

Tomasz

**Comment by abelsilva** [comment]
Hi Tomasz

First two issues are easily fixable.

Last one I didn't understand, on what conditions does that happen? 'no file gets returned'

Thanks
Abel

**Comment by abelsilva** [comment]
Hi Tomasz

check latest version 0.1.3 with fixes and let me know about your third issue

thanks
Abel

**Comment by tdjastrzebski** [comment]
Hi Abel,

the two issues appear to be fixed.

For the third one – screenshots and IE 11 F12 network capture file attached.

Basically, the http request does not go beyond sw1.png screenshot.

Is it “missing underscore-min.map”?

Thanks,

Tomasz

**Comment by abelsilva** [comment]
Hi Tomasz

attached files not included...

**Comment by tdjastrzebski** [comment]
Hi, files attached here again.
Tomasz

![sw3](https://cloud.githubusercontent.com/assets/7325277/14299720/5060c920-fb8c-11e5-8454-e40cd6d12dc5.png)
![sw1](https://cloud.githubusercontent.com/assets/7325277/14299719/505de57a-fb8c-11e5-9c61-a0c10713e944.png)
![sw2](https://cloud.githubusercontent.com/assets/7325277/14299721/5064fc8e-fb8c-11e5-9b1e-b54cbc24af92.png)

[NetworkData.txt](https://github.com/abelsilva/swaggerwcf/files/205432/NetworkData.txt)

**Comment by abelsilva** [comment]
can you try opening directly with the browser the swagger.json?

http://localhost:63780/api-docs/swagger.json

**Comment by abelsilva** [comment]
the .map file may be missing, it's not important, it's a mapping for the minified js file (used when opening the js debugger on the browser)

**Comment by abelsilva** [comment]
If you can see the swagger.json, can you go to:
http://editor.swagger.io/

and do `File \ Paste JSON` and input the contents to check if there is any error with it?

thanks
