### ISSUE TITLE
Nullable enum causes failure when generating swagger.json

### ISSUE THREAD

**Issue by ravikumarrao** [abelsilva/swaggerwcf#51]
As shown in the image, there is an error when swagger.json is created and the return type or the method argument type contains a nullable enum field/property in it. 

![image](https://cloud.githubusercontent.com/assets/5276563/20564368/f72b35f6-b1b2-11e6-8298-5368ef13cdb3.png)

**Comment by abelsilva** [comment]
new release checks for nullable types, can you check if your issue is fixed now?

**Comment by abelsilva** [comment]
assuming it's fixed... please reopen if you have any issue
