### ISSUE TITLE
Is it possible to change the host api for sample

### ISSUE THREAD

**Issue by davidverriere** [abelsilva/swaggerwcf#54]
Hi,
thanks for your great job.
Is it possible to have the hability to param the host of api sample.
Replace http://localhost/myapiendpoint by something else.
Or at least have api sample host equal to api doc host

Thanks

**Comment by abelsilva** [comment]
If you follow the installation guide, you will be adding SwaggerWcf to your own API.

SwaggerWcf will be available on the same location as your API, the only change will be the path

If you use 

```
 RouteTable.Routes.Add(new ServiceRoute("api-docs", new WebServiceHostFactory(), typeof(SwaggerWcfEndpoint)));
```

SwaggerWcf will be available at http://your.api.host/api-docs

Or maybe I didn't understand your question :)

**Comment by davidverriere** [comment]
Thanks for your help
My problem is I am using self hosting un windows service  with webhost and
my api endpoint url is generated by code.
I cant set endpoint of swagger because contract is internal .
Thanks

**Comment by abelsilva** [comment]
but whatever URL you end up configuring for your api endpoint dynamically should be the same for swaggerwcf, when you open http://*/api-docs, the swagger JSON will come from same place: http://*/api-docs/swagger.json

**Comment by abelsilva** [comment]
if you check this gist
https://gist.github.com/abelsilva/ac4ae0aeaf90c93adf0dcbaa6dca8cfa

After having this application running, I can access the api-docs using IPs or hostname and it will work
The swagger JSON url will also update based on the address I'm using

**Comment by davidverriere** [comment]
Thanks for your help
I can't use config file to define my enpoint, everithing is configured by code.
My api endpoint is https://localhost/EurekaDave/api/admin/supervisor/
My swagger documentation endpoint is https://localhost/EurekaDave/admin/api/docs/
Everthing works fine except samples 
![image](https://cloud.githubusercontent.com/assets/6039093/21270228/ffcad0d0-c3b5-11e6-851e-aea5e978c735.png)
Endpoint url in sample is https://localhost/supervisor, but my endpoint api url https://localhost/EurekaDave/api/admin/supervisor/ 

I would like set api base adresse for sample documentation when api documentation host is starting

Here how i am instantiating swagger endpoint
`            WebServiceHost apiHost = new WebServiceHost(typeof(SwaggerWcfEndpoint), new Uri[]
            {
                new Uri($"https://{this.machineName}/{ApiHostStarter.DispatchLicenseCode}/Admin/Api/Doc")
            });
            apiHost.Open();
`

**Comment by SeeSharp7** [comment]
Yes, you are able to change the path of your swagger api (but wcf base path must be the same). I'm also working in selfhosted services an this is the way, I create dynamic servicehosts. I hope, I can help you out.

`        private void CreateWebServiceHost<TContract, TBusiness>()
        {
            var webHost = new WebServiceHost(typeof(TBusiness), BuildServiceUri<TBusiness>());
            var webBinding = new WebHttpBinding { ContentTypeMapper = new CustomRawMapper() };
            var endpoint = webHost.AddServiceEndpoint(typeof(TContract), webBinding, string.Empty);
            var customHttpBehavior = new CustomHttpBehavior();

            endpoint.EndpointBehaviors.Add(customHttpBehavior);

            CustomizeWebServiceHost(ref webHost);

            _serviceHosts.Add(webHost);
        }

        private void CreateSwaggerServiceHost<TBusiness>()
        {
            var interfaces = typeof(SwaggerWcfEndpoint).GetInterfaces();

            if (interfaces.Length != 1)
                throw new InvalidOperationException("SwaggerWcfEndpoint implements more than one Interface! Only one contract is expected");

            var swaggerHost = new WebServiceHost(typeof(SwaggerWcfEndpoint), BuildSwaggerUri<TBusiness>());
            swaggerHost.AddServiceEndpoint(interfaces[0], new WebHttpBinding(), string.Empty);

            _swaggerHosts.Add(swaggerHost);
        }

        private Uri BuildServiceUri<TBusiness>()
        {
            var serviceUri = new Uri(_baseUri, $"{_serviceName}/v{GetServiceVersion<TBusiness>()}/");
            return serviceUri;
        }

        private Uri BuildSwaggerUri<TBusiness>()
        {
            var serviceUri = new Uri(_baseUri, $"{_serviceName}/v{GetServiceVersion<TBusiness>()}/{SwaggerUriSuffix}");
            return serviceUri;
        }`

**Comment by davidverriere** [comment]
Thanks for your help.
Swagger still works with endpoint adding by code but sample target the wrong url 
![image](https://cloud.githubusercontent.com/assets/6039093/21315598/3c5a8d4e-c5fd-11e6-8a0c-6410716635ca.png)
Endpoint url in sample is https://localhost/supervisor, but my endpoint api url https://localhost/**EurekaDave/api/admin**/supervisor/

I saw some post with javascript patch to workaround wrong uri sample.

**Comment by SeeSharp7** [comment]
Ah, okay! Maybe your problem is located here: 
- Check your Base Path defined in your swagger configuration section (app.config/web.config)
- Check the SwaggerWcfAttribute with Base Path, i. e. [SwaggerWcf("/myservice/v1")]

Are there differences between your endpoint uri?

**Comment by abelsilva** [comment]
let me know if you still need help to reopen the issue

**Comment by tmveni** [comment]
Hi, for SwaggerWcf there is any way to write dynamically instead of hardcoding the basepath, wanted to get from web.config/app.config file.
