### ISSUE TITLE
French accent issue with version 0.1.18

### ISSUE THREAD

**Issue by JFDionne** [abelsilva/swaggerwcf#55]
Hi, with version 18 if we put accent, like "é" on SwaggerWcfPath it's doesn't show correctly, see my picture below at point #2

Another small issue, if we put accent on the SwaggerWcfTag we cannot click on the "get" section, it not expend, see point #1. I think it's because of the URL.

![image](https://cloud.githubusercontent.com/assets/1706002/21099209/df66522a-c03a-11e6-8273-0b953429754a.png)

**Comment by JFDionne** [comment]
Oh, and the SwaggerWcfHidden don't seem to work on that version too, see what I put on issue #44

**Comment by abelsilva** [comment]
for point ```1```, issue seems to be from swagger ui, I created an issue:
swagger-api/swagger-ui#2561

For point ```2``` it's just a matter of changing the HTMLEncode

**Comment by abelsilva** [comment]
point `2` should be fixed now with new version
![image](https://cloud.githubusercontent.com/assets/1167088/21414143/4fb6940a-c7d3-11e6-9194-37f320d8eeca.png)

regarding point `1`, still needs an update from swagger-ui
