### ISSUE TITLE
Allow multiple of the same attribute

### ISSUE THREAD

**Issue by brunoj1** [abelsilva/swaggerwcf#56]
Hi,
I need multiple SwaggerWcfHeader on a method but i´m unable to do so.
Is there a way to do?

Thanks

**Comment by abelsilva** [comment]
Why aren't you able to do so?

**Comment by abelsilva** [comment]
Never mind, I just understood your issue

**Comment by SeeSharp7** [comment]
Hey, 
I know, what brunoj1 means. He wants to add multiple Header-Attributes on one operation. It's also an issue for me. I looked at your code and the only thing, that is missing in the attribute-definition (Attributes(/SwaggerWcfHeaderAttribute.cs) is the following (fat). Can you please fix this? 
`using System;

namespace SwaggerWcf.Attributes
{
    /// <summary>
    ///     Describe a parameter
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, **AllowMultiple = true**)]
    public class SwaggerWcfHeaderAttribute : Attribute`
