### ISSUE TITLE
ServicePath: SwaggerWcf.Attribute.SwaggerWcf() didn't accept string variable value

### ISSUE THREAD

**Issue by vincentnacar02** [abelsilva/swaggerwcf#57]
public class AppSettings
    {
        public static readonly string SwaggerBaseRestURL;
        static AppSettings()
        {
            SwaggerBaseRestURL = System.Configuration.ConfigurationManager.AppSettings["SwaggerBaseRestUrl"];
        }
    }

[SwaggerWcf.Attributes.SwaggerWcf(AppSettings.SwaggerBaseRestURL)] // error occurs here

**Comment by vincentnacar02** [comment]
That method only accept const value like this
[SwaggerWcf.Attributes.SwaggerWcf("/api/test/")] 
. The problem is when the site already deployed/publish how can we change the service path if it is hard coded ?

**Comment by abelsilva** [comment]
https://msdn.microsoft.com/en-us/library/aa288454(v=vs.71).aspx

Attribute parameters are restricted to constant values of the following types:
* Simple types (bool, byte, char, short, int, long, float, and double)
* string
* System.Type
* enums
* object (The argument to an attribute parameter of type object must be a constant value of one of the above types.)
* One-dimensional arrays of any of the above types

So, not possible to pass arguments to attributes that are not constant

**Comment by abelsilva** [comment]
Do you need to change the URL path?

Or is it about URL host?

**Comment by vincentnacar02** [comment]
I will use it in the url use to test Api method in Swagger UI.

**Comment by abelsilva** [comment]
but you need to change path or host?

**Comment by vincentnacar02** [comment]
The Path

**Comment by abelsilva** [comment]
Currently it is not possible in SwaggerWcf

**Comment by vincentnacar02** [comment]
Ok thanks.
