### ISSUE TITLE
Method Arrangement in Swagger UI

### ISSUE THREAD

**Issue by vincentnacar02** [abelsilva/swaggerwcf#60]
Hi Abel

Is there any way to arrange methods in swagger ui using attribute ?

Thanks

**Comment by SeeSharp7** [comment]
Hi,
what do you mean exactly with "arrange methods"? 
Swagger UI sorts your methods by it's path. When you use the Attribute [SwaggerWcfTag("YourGroupName")], you can specify method groups. Then you methods are arranged in groups. Will that solve your problem?

**Comment by vincentnacar02** [comment]
Hello,
Basically that [SwaggerWcfTag("YourGroupName")] is what I'm using right now, but my question, is there any way/options to sort by key/ or example i put and number sequence.

thanks

**Comment by SeeSharp7** [comment]
Hi, I don't think that there's a possibility to do so in the swagger 2.0 spec. I think, the only way, to add a feature like that, is to manipulate the swagger-ui and inject it:
`var fileStream = new FileStream(@"C:\Work\Playground\swagger-ui\swagger-ui.zip", FileMode.Open);
SwaggerWcfEndpoint.SetCustomZip(fileStream);`

**Comment by vincentnacar02** [comment]
Ohhh Okay. Thanks! Hope to add that option in future version of swagger I think that will be very useful.

**Comment by SeeSharp7** [comment]
Yeah! You can pronounce your feature request [here](https://github.com/swagger-api/swagger-ui). 
Has this solved the SwaggerWcf-Issue for you?

**Comment by abelsilva** [comment]
it there's still any issue please comment, I'll reopen
