### ISSUE TITLE
Issue in Installation

### ISSUE THREAD

**Issue by amrishmeet** [abelsilva/swaggerwcf#61]
when i tried to install the latest version got this error.
Could not install package 'SwaggerWcf 0.1.18'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Please Help

**Comment by SeeSharp7** [comment]
Hey, you are using a .net-framework version below 4.5. SwaggerWcf is not comiled for v 4.0. If you are using visual studio, rightclick your project, in which you want to reference SwaggerWcf. Under "Application" you need to setup your framework-version. Now retry adding the SwaggerWcf Nuget-Package. I am using .NET Framework 4.5.2 and it works fine. Try this out, I think, this will resolve your issue.

**Comment by amrishmeet** [comment]
Great..It works Thanks for the Help!!
