### ISSUE TITLE
Default Value in Property in Data Contract Class to Display at Model in Swagger UI

### ISSUE THREAD

**Issue by vincentnacar02** [abelsilva/swaggerwcf#62]
Hi ,

Just want to know is there any way to Set default value in property inside the Data Contract Class, and automatically display at Swagger UI Model?

Thanks

**Comment by abelsilva** [comment]
Hi

Do you mean this input area?
![image](https://cloud.githubusercontent.com/assets/1167088/21414234/ff8bfa46-c7d3-11e6-804c-914d3395ceb5.png)

**Comment by abelsilva** [comment]
If it is, then it is possible, as  you can see in the following snapshot:
![image](https://cloud.githubusercontent.com/assets/1167088/21414469/09d61eda-c7d6-11e6-8de3-461cebff01e1.png)

You can check using the following swagger file
https://gist.githubusercontent.com/abelsilva/11a1cd982c20fbf11d4cdf65e78bfd8f/raw/c7aae973eb759f826fa6862064ec64a6a016ede1/swagger.json

Currently I won't be implementing, but if you want to check it and submit a PR you're more than welcome

To start, you could use the the Attribute `DefaultValue`, e.g.:

```
        [DataMember]
        [Description("Book First Publish Date")]
        [DefaultValue(1990)]
        public int FirstPublished { get; set; }
```

And using that, add the default value to the definition class and output the default values on the serialization step

**Comment by vincentnacar02** [comment]
Oh Thanks! Great!
