### ISSUE TITLE
WCF service without DataContract/DataMember attributes in class

### ISSUE THREAD

**Issue by dyancat** [abelsilva/swaggerwcf#64]
Hi,

Is there any reason that classes without DataContract and DataMember attributes are not supported? My data types don't have any of these attributes, which is still supported by WCF. Ideally, I don't want to have to go through and add attributes to all of them to support swagger. 

I've tested that this works by removing the DataMemberAttribute check from DefinitionsBuilder.ProcessProperty and it generates the swagger documentation fine for my classes, but I'm not sure if there are other implications to doing this.

Support for this would be great.

Cheers

**Comment by abelsilva** [comment]
no special reason, just habit :)

new release in a moment without the requirement

thanks
