### ISSUE TITLE
Only One Get/Post Method Displayed (+ other minor issues)

### ISSUE THREAD

**Issue by ajmiam** [abelsilva/swaggerwcf#65]
Hi, I started using this library yesterday and today finally managed to get the documentation page to load.  However, there's a major problem:  The documentation doesn't show the methods I annotated with [SwaggerWcfTag] and [SwaggerWcfPath]; it instead picks a random GET method and a random POST method and only documents those.

The Situation:  Our solution consists of an ASP.NET webapp and a WCF Web Services class library project that's hosted as part of the webapp (I know because the <service> tags for its services appear in the ASP.NET webapp's web.confg rather than the WCF project's app.config).  Therefore, for Step 2 in the readme, I followed the instructions under "ASP.NET", adding 
`RouteTable.Routes.Add(new ServiceRoute("api-docs", new WebServiceHostFactory(), typeof(SwaggerWcfEndpoint)));`
to the ASP.NET project's Global.asax.cs Application_Start method.  I then decided to test the SwaggerWcf library by annotating a few of the many methods in our WCF services.  Let's call the two services I tried doing this to "ServiceA" and "ServiceB", which have interfaces "IServiceA" and "IServiceB".  So here's what I did:

1) Noted that` IServiceA `already has a `[ServiceContract]` tag on its interface declaration, and all of its methods already have `[OperationContract]` and `[WebInvoke]` attributes
2) Added a [SwaggerWcfPath("some path name", "some description")] attributes to one of those methods
3) Found the corresponding method implementation in `ServiceA` and added `[SwaggerWcfTag("ServiceA")]` and `[SwaggerWcfResponse(HttpStatusCode.OK, "Operation successful")]` to that method
4) Added `[SwaggerWcf("/serviceA")]` attribute to the declaration of class ServiceA
5) Repeated the above steps for ServiceB/IServiceB

What I expected:  The Swagger-UI documentation that appears when I visit (webapp base url)/api-docs would have a section named "ServiceA" and another named "ServiceB", each containing the one method I annotated, and displaying the description I put in the `[SwaggerWcfPath]` attribute.

What actually happened:  The documentation that appeared at that URL only had 1 section:  "default".  It contained a random GET method and a random POST method from ServiceA, and a random GET method and a random POST method from ServiceB.  Both of them displayed simply their respective base URLs passed to the `[SwaggerWcf]` attribute.  None of the methods were the one I documented.  In fact, the method shown from ServiceA didn't actually belong to ServiceA but to a subclass of ServiceA (as some of our services inherit other services--but note that each service, whether a base or derived class, is registered with its own <service> tag in web.config).  Also, the only way I could tell which methods actually showed up in the documentation is by their parameter type, which was of the form "TheEntireMethodNameInCamelCaseRequestWrapper". 

Here are the only oddities of our setup that I can think of as possible causes for this issue:

- Only annotating some of the web methods, not all of them?
- Having some service classes inherit others?
- Not including the "UriTemplate" property in our `[WebInvoke]` tags?

If you have an idea of what could be causing the issue, I'd greatly appreciate it!  Thanks!  I know this library will be a big help for my team once we can get it working.

Another minor question:

I can't seem to find the "swagger.json" file that this library generates.  I did a file search and it doesn't seem to be anywhere in our solution's source or output trees.  Does this library not actually generate a file, but instead just store the documentation in memory and return it whenever the api-docs route is called?  Is there some way I can get it to save the file to disk?

Also, is there a way to make the swagger-ui page have all its sections expanded by default, instead of collapsed?

**Comment by abelsilva** [comment]
please post your functions 'declarations' with the SwaggerWcf attributes

swagger.json doesn't exist in the filesystem, only in memory
If you need it, when everything is working you can open the URL and save it

**Comment by abelsilva** [comment]
closing, let me know if you still have any issues
