### ISSUE TITLE
Multiple Service Versions

### ISSUE THREAD

**Issue by fayrena** [abelsilva/swaggerwcf#67]
Hi, thank you for the great package! 

I have one service with two major versions. Is it possible to configure two seperate swagger uis for the service? If I configure two uis, both of them view the methods of both versions. They also have the same swagger.json. 

Thanks!

**Comment by SeeSharp7** [comment]
👍

**Comment by abelsilva** [comment]
Hi

Currently not supported, SwaggerWcf starts scanning everything and storing all functions/types/etc.
To support this a lot had to be changed to know the 'context' (service) being scanned

**Comment by fayrena** [comment]
Hi, 

I created a pull request to support multiple service versions. 
It would be great if you could review it.

Thank you!
