### ISSUE TITLE
Override parameter type

### ISSUE THREAD

**Issue by QuickOla** [abelsilva/swaggerwcf#69]
I have a post method that has a Stream parameter, but I would like to override this in the Swagger desription to actually display the List<object> that the stream represent. Is this possible, and if so, how do I do I configure it?

**Comment by abelsilva** [comment]
can you check if this works for you?

https://github.com/abelsilva/swaggerwcf/issues/15#issuecomment-227867152

**Comment by abelsilva** [comment]
closing...
