### ISSUE TITLE
Store.svc Endpoint showing a None Message Version error

### ISSUE THREAD

**Issue by Chaasof** [abelsilva/swaggerwcf#71]
Hello, 

I'm trying to run your solution and see the store example doc but I always have :  '...does not have a Binding with the None MessageVersion' with http://localhost:52331/Store.svc

**Comment by abelsilva** [comment]
I have no idea, without the code I can't help

**Comment by abelsilva** [comment]
reopen if you still have issues

**Comment by poulad-rbc** [comment]
@Chaasof Did you find a way to fix this?

**Comment by poulad-rbc** [comment]
Below is the error WCF Test Client displays. I have the HEAD of master at the moment.

**The endpoint at 'http://localhost:52331/Store.svc' does not have a Binding with the None MessageVersion. ÿ'System.ServiceModel.Description.WebHttpBehavior' is only intended for use with WebHttpBinding or similar bindings.**

**Description**: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

**Exception Details**: System.InvalidOperationException: The endpoint at 'http://localhost:52331/Store.svc' does not have a Binding with the None MessageVersion. ÿ'System.ServiceModel.Description.WebHttpBehavior' is only intended for use with WebHttpBinding or similar bindings.
