### ISSUE TITLE
Endpoint doesn't show up in the swagger ui when using self-hosted WCF service

### ISSUE THREAD

**Issue by finidigeorge** [abelsilva/swaggerwcf#72]
Hi,

I'm trying to add swagger to an self-hosted WCF app, swagger ui is working fine, but I couldn't add a wcf service method information there. So, I did like your documentation says:
1. Added swagger service to the app.config:
`<service name="SwaggerWcf.SwaggerWcfEndpoint">
        <endpoint address="http://localhost:58960/docs" binding="webHttpBinding" contract="SwaggerWcf.ISwaggerWcfEndpoint" />      
</service>`

2. Added SwaggerWcfPath attribute to the method description interface
3. Added `[AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
    [SwaggerWcf("/v1/rest")]` attributes to the service class
4. Added SwaggerWcfTag and SwaggerWcfResponse attributes to the same method as in item 2 from this list

As a result, I see the swagger ui when following the http://localhost:58960/docs url, but without any methods information

**Comment by abelsilva** [comment]
Does your `http://localhost:58960/docs` URL redirect to `http://localhost:58960/docs/index.html?url=http://localhost:58960/docs/swagger.json` ?

**Comment by finidigeorge** [comment]
Yes, it does, but url a bit different: `http://localhost:58960/docs/index.html?url=/docs/swagger.json`

**Comment by abelsilva** [comment]
ok, looks correct, and what is the content of http://localhost:58960/docs/swagger.json ?

**Comment by finidigeorge** [comment]
Just `{"swagger":"2.0","info":{"version":"0.0.1","description":"Sample Service to test SwaggerWCF"}}`
Sorry for the late answer

**Comment by abelsilva** [comment]
hi

sorry also for the late answer, can you show the interface and the class ?

**Comment by finidigeorge** [comment]
Hi, I've created a separate class for this, as an example. So:
Interface:
    [ServiceContract]    
    public interface ICalendarRestService
    {
        [OperationContract]
        [SwaggerWcfPath("Get list of calendars")]
        [WebInvoke(Method = "GET",
            RequestFormat = WebMessageFormat.Json,
            ResponseFormat = WebMessageFormat.Json,
            BodyStyle = WebMessageBodyStyle.Bare,
            UriTemplate = "/calendars")]
        IList<string> GetCalendarList();
        
    }

Class:

    [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
    [SwaggerWcf("/v1/calendars")]
    public class CalendarRestService : BaseRestService, ICalendarRestService
    {        
        [SwaggerWcfTag("Calendars")]
        public IList<string> GetCalendarList()
        {
           ...
        }

        
    }

**Comment by abelsilva** [comment]
I tried implementing from scratch your example and it is working

Adding a zip file with a VS2017 solution with your example
[SwaggerWcfTest.zip](https://github.com/abelsilva/swaggerwcf/files/894246/SwaggerWcfTest.zip)

**Comment by finidigeorge** [comment]
Thanks for this sample project, I finally found out what I did wrong - forgot to add config section to the app.config. 

Thank you so much for your help
