### ISSUE TITLE
Provide support for path and query parameters.

### ISSUE THREAD

**Issue by thecolour** [abelsilva/swaggerwcf#74]
From this stackoverflow question: http://stackoverflow.com/questions/43872506/change-parameter-type-in-swaggerwcf

Swagger allows setting the parameter type but with SwaggerWcf I can't edit this file, it's generated. It's set to body by default, but I need it to be path.

One might think SwaggerWcfParameterAttribute would allow setting this. But it only allows Description and Required.

How can it be set specifically?

**Comment by abelsilva** [comment]
support for path parameters:
https://github.com/abelsilva/swaggerwcf/blob/master/src/SwaggerWcf.Test.Service/IStore.cs#L48

isn't this what's expected?

**Comment by thecolour** [comment]
Thanks for your quick response. Closing this call.
