### ISSUE TITLE
Trying to add swaggerwcf to a WCF Service Application

### ISSUE THREAD

**Issue by Drahcir9000** [abelsilva/swaggerwcf#75]
Hello and thank you for developing and sharing swaggerwcf!

I am currently trying to add swaggerwcf to a WCF Service Application. Therefore I followed all the steps in the Getting Started doku. I have tried both, the ASP.NET and Self Hosted approach, but none work until now.

The ASP.NET approach works locally with the limitation, that I have to call at least one service function to trigger its Constructor where I call RouteTable.Routes.Add(...); . If I try to deploy the dlls to my server, call one function and try to call http://host:port/service/api-docs I receive the error message that there is another protocolMapping-entry with the key=http. This is necessary for the service. If I remove the entry the error message is replaced by an error 404.

On the other hand, when I try the Self Hosted approach I am confronted with the error message "The contract name 'SwaggerWcf.ISwaggerWcfEndpoint' could not be found in the list of contracts implemented by the service 'DCI4FileHandlerService'."

I already searched the forum for any solutions but none helped. Can you give me any advice?

Regards

**Comment by abelsilva** [comment]
Download the sample service, does it work when you start it?

If so, start changing it to match what you want and you'll figure out what's the issue

**Comment by abelsilva** [comment]
closing, please reopen if still having issues

**Comment by abhimanyuk453** [comment]
tried to implement the swagger for wcf but unable to implement. Could you help me to implement swagger for my wcf applicaton.
Thanks,
Abhi
