### ISSUE TITLE
duplicated mapping key

### ISSUE THREAD

**Issue by rahrs** [abelsilva/swaggerwcf#76]
Thanks for making this!

We're having some trouble with the generated swagger.json,

"duplicated mapping key", the headers descriptions are all dublicated

heres the generated json
`"responses": {
					"401": {
						"description": "Unauthorized"
					},
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/planorama.Resources+Resource"
						}
					},
					"400": {
						"description": "Bad Request"
					},
					"401": {
						"description": "Unauthorized"
					},
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/planorama.Resources+Resource"
						}
					},
					"400": {
						"description": "Bad Request"
					}
				}`

and heres the method decoration
`[SwaggerWcfTag("Tests")]
        [SwaggerWcfPath("Test metode")]
        [SwaggerWcfResponse(HttpStatusCode.OK, "OK"), SwaggerWcfResponse(HttpStatusCode.BadRequest, "Bad Request", true), SwaggerWcfResponse(HttpStatusCode.Unauthorized, "Unauthorized", true)]
        [WebInvoke(Method = "GET", UriTemplate = "", ResponseFormat = WebMessageFormat.Json)]`

**Comment by rahrs** [comment]
I think it only happens when you dont define your own interface for the wcf service, like

[ServiceContract]
    [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
    [ServiceBehavior(InstanceContextMode = InstanceContextMode.PerCall)]
    [SwaggerWcf("/test")]
    public class TestService

**Comment by abelsilva** [comment]
new version 0.1.24 released a fix for this issue

thanks for reporting the issue! 👍
