### ISSUE TITLE
WCF with SAme uri for GET / POST only shows WebGET not WebInvoke Methods

### ISSUE THREAD

**Issue by WzBn** [abelsilva/swaggerwcf#79]
Hi, I'm not sure if it is a problem with the configuration.. but I've a wcf that has two diferents method to handle the GET and the POST for the same uritemplate, one using WebGet and another using WebInvoke. En the SwaggerUI only is reported the GET operation.

**Comment by jagdaleganesh** [comment]
Do you know How I can see help file which is generated?

**Comment by WzBn** [comment]
Thanks for answering, I'not sure how I can share the Help generated, because it is and Intranet Web application. Anyway I added some screenshots

capturewebapi001 and capturewebapi002 Shows help data generated

capturewebapi003 Shows definitions of the WebInvoke NO Reported and capturewebapi004 Shows definitions of the WebGet Reported.

finally capturewebapi005 shows config section on the Web.config

Thanks again in advance. Leo

![capturewebapi005](https://user-images.githubusercontent.com/29458492/27910948-b499b574-622d-11e7-8848-419fcf2d0d43.PNG)
![capturewebapi004](https://user-images.githubusercontent.com/29458492/27910837-37d69818-622d-11e7-9dc1-5cd69879cf6c.PNG)
![capturewebapi003](https://user-images.githubusercontent.com/29458492/27910840-37d7d796-622d-11e7-8bfa-e0306695c056.PNG)
![capturewebapi002](https://user-images.githubusercontent.com/29458492/27910838-37d7178e-622d-11e7-930e-6ad116169847.PNG)
![capturewebapi001](https://user-images.githubusercontent.com/29458492/27910839-37d6fe7a-622d-11e7-910d-166e98d010a1.PNG)

**Comment by abelsilva** [comment]
in your WebInvoke, can you check if changing `Method="*"` to `Method="POST"` solves the issue?

**Comment by abelsilva** [comment]
Could be a problem from here
https://github.com/abelsilva/swaggerwcf/blob/4dade22379f67ece4ec27c249649cc6f16d81c53/src/SwaggerWcf/Support/Mapper.cs#L129

**Comment by WzBn** [comment]
Thanks a Lot, that was the issue.  Method:="*" is not handled correctly, but Method:="POST" works Ok. 

Thanks a lot

**Comment by jagdaleganesh** [comment]
If possible that help page url , just for sample.? is it something like http://localhost/wcfHost/api-docs?
I have configured this in ASP.net hosting for wcf rest, with http://localhost/wcfHost/api-docs url i am not seeing the same page which you have shared above.

Thanks,

**Comment by abelsilva** [comment]
@jagdaleganesh if you are having any problem report on a different issue please
