### ISSUE TITLE
incorrect swagger file generated

### ISSUE THREAD

**Issue by tdjastrzebski** [abelsilva/swaggerwcf#8]
Hi Abel,
I open another issue since it ieasier for me to communicate via github.
Indeed, the generated swagger file does not validate with http://editor.swagger.io
File attached.
[swagger.json.txt](https://github.com/abelsilva/swaggerwcf/files/208028/swagger.json.txt)
BR,
Tomasz

**Comment by abelsilva** [comment]
can you show me the signature for
`POST` `/v1/rest/sots/{timestamp}`

**Comment by tdjastrzebski** [comment]
[OperationContract]
[WebGet(ResponseFormat = WebMessageFormat.Json, UriTemplate = "sots/{timestamp}")]
SOTObject[] GetSOTsForUser(string timestamp);

**Comment by abelsilva** [comment]
that's for the `GET` operation, don't you have another function for the `POST` ?

the swagger json shows another one (or maybe it's a bug when parsing functions)

```

    "/v1/rest/sots/{timestamp}": {
      "get": {
        "consumes": [ "application/xml" ],
        "produces": [ "application/json" ],
        "parameters": [
          {
            "name": "timestamp",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "default": {
            "description": "not available",
            "schema": {
              "type": "array",
              "items": { "$ref": "#/definitions/Company.SOT.DataMembers.SOTObject" }
            }
          }
        }
      },
      "post": {
        "consumes": [ "application/xml" ],
        "produces": [ "application/json" ],
        "parameters": [
          {
            "name": "sotObjects",
            "in": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/Company.SOT.DataMembers.SOTObject[]" }
          },
          {
            "name": "timestamp",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "default": {
            "description": "not available",
            "schema": {
              "type": "array",
              "items": { "$ref": "#/definitions/Company.SOT.DataMembers.SOTObject" }
            }
          }
        }
      }
    },
```

**Comment by abelsilva** [comment]
I'm suspecting an issue when we have an array as a parameter in the body

```
        "parameters": [
          {
            "name": "sotObjects",
            "in": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/Company.SOT.DataMembers.SOTObject[]" }
          },
```

the schema should probably be:

```
"type": "array",
"items": { "$ref": "#/definitions/Company.SOT.DataMembers.SOTObject" }
```

but first show me the `POST` function just to be sure

**Comment by tdjastrzebski** [comment]
That is right, here is the POST method.
[OperationContract]
[WebInvoke(ResponseFormat = WebMessageFormat.Json, UriTemplate = "sots/{timestamp}", Method ="POST" )]
SOTObject[] SubmitSOTs(SOTObject[] sotObjects, string timestamp);

**Comment by abelsilva** [comment]
yes, that's it, the definition of the array is wrong.

after changing it and removing this definition from the json:
```
    "Company.SOT.DataMembers.SOTObject[]": {
      "type": "array",
      "items": { "$ref": "#/definitions/" }
    },
```

the json is valid in the swagger editor

I'll look into it, thanks for the help
