### ISSUE TITLE
Override method input parameter type

### ISSUE THREAD

**Issue by anibal-acosta** [abelsilva/swaggerwcf#80]
Some times, in REST API we use Stream as method parameter, then we deserialize the stream content to object type but in swaggerWcf we can't define that this stream param is of particular type. Return type can be defined (look example) but request param type not.

For example:

```
[SwaggerWcfReturnType(typeof(CustomerWebCallResponse))]
public Stream SendMessage(String userId, Stream message)
{
}
```
will be nice to have something like this...
` [SwaggerWcfRequestParamType("message", typeof(CustomerWebCallRequest))]`

**Comment by abelsilva** [comment]
can you check if new version 0.1.25 works for you?

Use the following syntax:
```
[SwaggerWcfReturnType(typeof(CustomerWebCallResponse))]
public Stream SendMessage(String userId, [SwaggerWcfParameter(ParameterType = typeof(CustomerWebCallRequest))] Stream message)
{
    ///
}
```
