### ISSUE TITLE
How to see help files

### ISSUE THREAD

**Issue by jagdaleganesh** [abelsilva/swaggerwcf#81]
Hi ,
I have configured every as shown in the documents. Also I am able to service running on http://localhost/testapp/api-docs.
But I do not know how I can see help page. Can you please give me the URL so that I can see help docs or how to create swagger json file?

I am eagerly waiting for your answer.

Thanks,
Ganesh

**Comment by abelsilva** [comment]
if you configured as explained in the docs, that URL is the one for the help page

**Comment by jagdaleganesh** [comment]
When I browse that URL , it just shows as WCF information. Actually I want to import those API to azure API management which needs json file. Is that the URL which gives me json file if I use it in Azure import api?

**Comment by abelsilva** [comment]
send a screenshot of what you are seeing

**Comment by jagdaleganesh** [comment]
![2017-07-06 19_51_45-service - internet explorer](https://user-images.githubusercontent.com/2612947/27915680-a46bd09a-6284-11e7-8a9d-3f470ee7062d.png)

**Comment by abelsilva** [comment]
that's not the SwaggerWcf page, you have something wrong with your WCF application

I would suggest you start with the sample one in the repository and change to your needs until you understand what's causing the issue

**Comment by jagdaleganesh** [comment]
[WebApplication1.zip](https://github.com/abelsilva/swaggerwcf/files/1129948/WebApplication1.zip)

Please see the attached web application in which I have tried to integrate swagger. Can you please what I did wrong , Please?

Is it mandatory to have WCF application? I have tried with MVC web application.

**Comment by jagdaleganesh** [comment]
Now I came to know that I was using ServiceHostFactory instead of WebServiceHostFactory, for this i have to system.serviceModel.web.

Now http://localhost:52269/api-docs is redirectiing to http://localhost:52269/api-docs/index.html?url=/api-docs/swagger.json but it is showing HTTP Error 404.0 - Not Found. Looks like index.html is not getting generated or may be hosting server is not able to find out index.html file. Do you know what is the reason?

**Comment by jagdaleganesh** [comment]
[WebApplication1.zip](https://github.com/abelsilva/swaggerwcf/files/1129969/WebApplication1.zip)
 I have reattached the same application by correcting it to WebServiceHostFactory, just to reproduced index.html not found issue.

**Comment by jagdaleganesh** [comment]
I have checked for WCF application and it is working as exptected but not working for MVC web application. Please see the above attachment to reproduced. Please let me know How I can remove this limitation.
Thanks

**Comment by abelsilva** [comment]
please start with the sample in the repository, that one works, keep changing until you get what you want (or until you find your issue)

**Comment by jagdaleganesh** [comment]
Actually I have tried everything from side , but I am not able to get why Index.html is not find when this swagger using in Webapplication. 
I have also tried to debug and found how html pages rendered dynamically. 
Do you have any idea, why in only webapplication can not find index.html page from embedded resource of swagger dll?
below is the code snippet where it try to redirect to Index.html .
     if (string.IsNullOrWhiteSpace(content))
            {
                string swaggerUrl = woc.IncomingRequest.UriTemplateMatch.BaseUri.LocalPath + "/swagger.json";
                woc.OutgoingResponse.StatusCode = HttpStatusCode.Redirect;
                woc.OutgoingResponse.Location = "index.html?url=" + swaggerUrl;
                return null;
            }

**Comment by abelsilva** [comment]
did you try the test project in the repository?

**Comment by jagdaleganesh** [comment]
Yes, that project is working. That project type is "WCF service application" and but when I tried in MVC or ASP.net web application it is not working.. it gives index.html not found.

**Comment by abelsilva** [comment]
can't help you on that, I don't have know-how with MVC applications on ASP.net

**Comment by poulad-rbc** [comment]
I had the same problem with getting 404 errors and figured that enabling directory browse in `web.config` fixes that.

```xml
<directoryBrowse enabled="true"/>
```
