### ISSUE TITLE
Marking interfaces with SwaggerWcf attribute

### ISSUE THREAD

**Issue by heXelium** [abelsilva/swaggerwcf#82]
I have single SeviceType, lets call it `ServiceType1` for example, that implements two interfaces `Interface1`and `Interface2`. Both of them marked with `[ServiceContract]` attribute. The problem is that they are exposed to the world under different endpoints:
```
 <endpoint address="http://localhost/api/service1" binding="webHttpBinding" contract="Interface1" />
 <endpoint address="http://localhost/api/service2" binding="webHttpBinding" contract="Interface2" />
```
I didn't find a way how to handle correct paths generation. If I mark `ServiceType1` with `[SwaggerWcf("/api")]` the services part is missing in urls. Other way if I mark only interfaces with `[SwaggerWcf("/api/service1")]` and `[SwaggerWcf("/api/service2")]` respectively, as documentation says interfaces are supported, generation fails with error.

Eventually I've looked in the code where it fails and following statement looks odd to me
```
if (i.IsInterface)
{
   InterfaceMapping map = serviceType.GetInterfaceMap(i);
   pathActions.AddRange(GetActions(map.TargetMethods, map.InterfaceMethods, definitionsTypesList));
}
```
because `i` and `serviceType` is same type if interface was marked with `[SwaggerWcf]` attribute.

Could you please suggest how to deal with this situation?

**Comment by abelsilva** [comment]
I checked and yes, it doesn't work

I would suggest to create two classes to expose with WCF and have them call your existing class

**Comment by heXelium** [comment]
Thank you. Yes it's way to go but I will preffer not to do so. Are you going to fix it in any way?

**Comment by abelsilva** [comment]
I won't be working on it, although feel free to send a PR

**Comment by abelsilva** [comment]
let me know if anything doesn't work
