### ISSUE TITLE
How to add comments/description of fields of data model?

### ISSUE THREAD

**Issue by sunil543** [abelsilva/swaggerwcf#84]
#Address is data model object. it's contains set fields like Housenumber, Street,city,country.
So, i want to apply few comments on dofferent fields for Easy to understand programmers

**Example: Adding comments on few fields like StreetName, HouseNumber ......**
{
  "Address": {
    "PostalCode": "string", 
    "CountryId": 0,
    "IsPreferred": true,
    "BuildingName": "string",
    "CityName": "string",
    **"StreetName": "string", //SG side Area, HK&TH side Road**
    "ApartmentNumber": "string",
    **"HouseNumber": "string", //SG side Unit number**
    "BlockNumber": "string",
    "EstateName": "string"
	}
}
public Address GetAddress(string postalcode)
{

return Address;
}

**Comment by abelsilva** [comment]
please read the docs (Attributes table) or check the sample service, this is supported
