### ISSUE TITLE
How to apply new line or Break or multi line in description of any swagger attribute

### ISSUE THREAD

**Issue by sunil543** [abelsilva/swaggerwcf#85]
How to apply break line in description?
  [SwaggerWcfPath("Delete author", "Delete an author on the store")]
Delete an author on the store
To

UI Side
Delete
an
author
on
---
---

**Comment by abelsilva** [comment]
Hi

processing from swagger ui is done using markdown syntax
you can probable get what you want using:

```
[SwaggerWcfPath("Delete author", "Delete\r\n\r\nan\r\n\r\nauthor\r\n\r\non\r\n\r\r\nthe\r\n\r\nstore")]
```

Result:
![image](https://user-images.githubusercontent.com/1167088/28491278-b20f962c-6ec4-11e7-8682-2e80e5c58197.png)

Note: you may use other markdown syntax like headers, lists, etc

**Comment by sunil543** [comment]
This is not works.
Added new line tags not workind..

**Comment by sunil543** [comment]
Thanks!
Working
