### ISSUE TITLE
how to apply SwaggerWcfTag to service implementation level so that all methods in that service will come under one tag

### ISSUE THREAD

**Issue by jagdaleganesh** [abelsilva/swaggerwcf#86]
Hi,
Currently I need to apply SwaggerWcfTag to apply for each method inside service implementation class. I want to apply SwaggerWcfTag one time i.e at class level so that all methods comes under the same tag and no need to apply at each method.

**Comment by abelsilva** [comment]
not supported, you may submit a PR for it if you wish
