### ISSUE TITLE
OperationId generated duplicated if WCF has overloaded method

### ISSUE THREAD

**Issue by jagdaleganesh** [abelsilva/swaggerwcf#87]
Hi,
How I can override OperatioId generation if WCF service has overloaded method? I can not modified overloaded method as those method used by multiple clients.

Thanks,

**Comment by abelsilva** [comment]
please post a sample, not sure I understand exactly what you're trying to do

**Comment by abelsilva** [comment]
closing, please send an update if you still want to open this
