### ISSUE TITLE
Support for task-async operations on the service.

### ISSUE THREAD

**Issue by JonasSyrstad** [abelsilva/swaggerwcf#9]
Nice tool, just one little request:

the following method will expose the Task<T> as the return type, where it should get the type of 'T' and reflect that.
`[OperationContract]
        [WebInvoke(BodyStyle = WebMessageBodyStyle.Bare, RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json, UriTemplate = "Sample/", Method = "POST")]
        [SwaggerWcfPath("Sample", "Post a sample")]
        Task<SampleType> Sample(SampleType sampleMessage);`

**Comment by abelsilva** [comment]
new version is pushed to nuget, let me know if you still have issues

Thanks!
