### ISSUE TITLE
Display Issues on Swagger UI for WrappedRequest Parameter

### ISSUE THREAD

**Issue by nshrivastava79** [abelsilva/swaggerwcf#90]
First of all thanks for contributing on this library. It is really helpful. I found a couple of issues which show up when I use a WrappedRequest parameter on the method.

1) In the code, body parameter is created on the fly which is working as expected but while creating name of parameter, it uses Name as implementation.Name + "RequestWrapper"

operation.Parameters.Add(new ParameterSchema
                    {
                        Name = implementation.Name + "RequestWrapper",
                        In = InType.Body,
                        Required = true,
                        SchemaRef = typeFormat.Format
                    });

This causes long parameter names and which disturbs the CSS of the Swagger UI as shown below and eventually end up hiding some of the information on the page. 

![image](https://user-images.githubusercontent.com/3211166/29495604-5df4077a-8577-11e7-9a48-4dc65a7fde46.png)

It would be nice to have column with fixed width and wrap the parameter name. If that is not possible, it is possible to shorten the naming format for Wrapped Request? Due to this important information i.e sample value for parameter is hidden on the page. 

2) For the above, could it have used the actual name of parameter specified to be Wrapped? I had method signature like this so having ClientData as name of parameter in the output would have been better.

[WebInvoke(UriTemplate = "/CompleteWorkItem/{workItemID}", Method = "POST", BodyStyle = WebMessageBodyStyle.WrappedRequest)]
WFEvent CompleteWorkItem([SwaggerWcfParameter(Required = true, Description = "WorkItemID", ParameterType = typeof(string))]string workItemID, [SwaggerWcfParameter(Required = false, Description = "ClientData", ParameterType = typeof(string))]string clientData); 

3) The WrappedRequest code always sets body parameter to true as it is hardcoded. It is possible to read it from the Parameter definition?  In my case clientData is optional but shows as required on the UI.

Any help on these would be highly appreciated.

**Comment by abelsilva** [comment]
the web interface is from swagger ui, I don't make any changes to it.

SwaggerWcf just packages the dist from swagger ui

**Comment by nshrivastava79** [comment]
Thanks for the reply. Would it be possible for you to consider a small change in code in mapper.cs file. That takes care of the problem. I just inserted 4-5 lines to strip out the namespace if it is included in the name. Rest of code is same as what you had. This gives a cleaner display as shown below.

if (wrappedRequest)
                {
                    TypeFormat typeFormat = Helpers.MapSwaggerType(typeBuilder.Type, definitionsTypesList);

                    int indexofDot = implementation.Name.LastIndexOf('.');
                    string methodName;
                    if (indexofDot >= 0)
                        methodName = implementation.Name.Substring(indexofDot + 1) + "RequestWrapper";
                    else
                        methodName = implementation.Name + "RequestWrapper";

                    operation.Parameters.Add(new ParameterSchema
                    {
                        Name = methodName,
                        In = InType.Body,
                        Required = true,
                        SchemaRef = typeFormat.Format
                    });
                }

![image](https://user-images.githubusercontent.com/3211166/29581610-b7a55996-872e-11e7-93e7-913e70142cb8.png)

Looking forward to your feedback and your help on this is really appreciated.

**Comment by abelsilva** [comment]
sorry for the long delay,

please send me a complete example with your issue, I'm not able to reproduce the issue in the first post

**Comment by nshrivastava79** [comment]
I found the root cause of the issue. If you implement the interface explicitly in the implementation class, it shows fully qualified name for wrapper object but if you have implicit interface implementation, it shows only wrapped method name. If you look at the code I mentioned in previous post, above it will work even with explicit interface.

Here are more details

#1: When interface is implemented implicitly

![implicit -1](https://user-images.githubusercontent.com/3211166/30767426-4ec812a6-9fb1-11e7-9f44-3964f3593116.jpg)

![implicit -2](https://user-images.githubusercontent.com/3211166/30767431-54237c54-9fb1-11e7-95cc-44b4a0142aec.jpg)


#2: When interface is implemented explicitly:

 
![explicit - 1](https://user-images.githubusercontent.com/3211166/30767433-5a25f816-9fb1-11e7-9a3f-15852d2b20f2.jpg)

![explicit - 2](https://user-images.githubusercontent.com/3211166/30767439-5eb0468e-9fb1-11e7-8d0e-b871c1799bc9.jpg)

**Comment by abelsilva** [comment]
check latest release, let me know if you still have any issues

**Comment by abelsilva** [comment]
not sure if fixing #107 will cause some issues here, I'm going to force `FullName` on the object types when the `SwaggerWcfDefinition` attribute doesn't have a `ModelName`
