### ISSUE TITLE
Few issues with array of primitive type as return type

### ISSUE THREAD

**Issue by nshrivastava79** [abelsilva/swaggerwcf#91]
If the return type of a method is set as array of a primitive type, there are couple of minor issues which I noticed

1) If I have a return type set as String[], on swagger UI the model is shown properly but it would be nice if example was shown as 
[ 
    "String" 
]

It currently shows as 

[
      null
]

which can be confusing for user till he goes and checks out the model. It might be something coming from Swagger UI but just want to check if you have any way of passing correct value in example for array.

2) If I return array of byte for e.g. 

byte[] GetRegisteredUserIcon(string username)

The return value being detected is array of string. Is that expected?

![image](https://user-images.githubusercontent.com/3211166/29599368-0db9cbd2-8784-11e7-88d2-7a3567ad8bce.png)

**Comment by abelsilva** [comment]
for 1) send me an example of the declared function in class and interface

for 2) it's normal, there's no 'byte' type in JSON

**Comment by nshrivastava79** [comment]
Interface
[SwaggerWcfPath("GetAccessRightNames", "Gets a list of access rights.")]
        [SwaggerWcfTag("Admin")]
        [SwaggerWcfSecurity("basicAuth")]
        [SwaggerWcfHeader(name: "appID", required: false, description: "Unique Application ID", defaultValue: "")]
        [SwaggerWcfHeader(name: "locale", required: false, description: "User Locale", defaultValue: "")]
        [SwaggerWcfResponse(HttpStatusCode.OK, "Request processed successfully")]
        [SwaggerWcfResponse(HttpStatusCode.BadRequest, "Bad request", true)]
        [SwaggerWcfResponse(HttpStatusCode.InternalServerError, "Internal server error", true)]
        [SwaggerWcfResponse(HttpStatusCode.Unauthorized, "Unauthorized access", true)]
[WebGet(UriTemplate = "/GetAccessRightNames")]
        String[] GetAccessRightNames();

Class def

public string[] GetAccessRightNames()
        {
            //code
        }

**Comment by abelsilva** [comment]
please check latest version, is showing me:
![image](https://user-images.githubusercontent.com/1167088/30887027-0404f706-a2f0-11e7-8ecf-21700f5ce620.png)
