### ISSUE TITLE
Issue parsing JSON file through Microsoft Flow

### ISSUE THREAD

**Issue by nshrivastava79** [abelsilva/swaggerwcf#93]
I have a couple of methods which return an array of string, int and byte. While reading the generated swagger file, I get parsing error on the methods which return array of string and int but works fine for the array of byte. Am I missing something?

It is looking for the definition for string and int in definitions section

#/definitions/System.Int32' is referenced but could not be found in the swagger.

#/definitions/System.String' is referenced but could not be found in the swagger.

Byte works because it got generated in definitions section

"System.Byte": 
{
"type": "string",
"format": "byte"
},

Any pointers on what could be wrong? 

For testing purpose I removed those 3 methods but I ran into another issue

The request failed with error: 'Parsing error(s): JSON is valid against more than one schema from 'oneOf'. No valid schemas. Path 'securityDefinitions.basicAuth'

No errors show up in Swagger UI and it works as expected with basic Auth. Any help would be highly appreciated.

**Comment by nshrivastava79** [comment]
So I found the resolution to 2nd issue. It was coming in SecurityDefinitions.basicAuth element as I had specified name parameter for it which seems to be be invalid for swagger 2.0 spec though if I validate it in online validator it shows no error for Swagger 2.0 schema.

http://www.jsonschemavalidator.net/

Commenting that out worked. 

var security = new SecurityDefinitions
                {
                    {
                        "basicAuth", new SecurityAuthorization
                        {
                            Type = "basic",
                            //Name = "basicAuthentication",
                            Description = "Forces authentication with basic authentication credentials.",
                        }
                    }
                };

I am still stuck with issue around String and Int arrays as return type so any help on that will be appreciated.

**Comment by abelsilva** [comment]
can you check with the new release the issue 1) ?

Thanks

**Comment by nshrivastava79** [comment]
Issue #1 is fixed with new package. Thanks a lot for your help.
