### ISSUE TITLE
If UriTemplate is omitted, URI path does not include method name

### ISSUE THREAD

**Issue by colbroth** [abelsilva/swaggerwcf#96]
If UriTemplate is not included in WebInvoke, the path does not include the method name. Expected the path to include the method name. When UriTemplate is not included, the default rules are that the URI will include the endpoint of the service plus the name of the method.

For example, in the SwaggerWcf.Test.Service, if I omit the UriTemplate from the CreateBook method, the URI extracted will be /v1/rest. Expected the URI extracted to be /v1/rest/CreateBook.

Change this method:
```
        **[WebInvoke(UriTemplate = "/books", BodyStyle = WebMessageBodyStyle.Wrapped, //Method = "POST",
            RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]**
        [OperationContract]
        Book CreateBook([SwaggerWcfParameter(Description = "Book to be created, the id will be replaced")] Book value);
```

To:
```
        **[WebInvoke()]**
        [OperationContract]
        Book CreateBook([SwaggerWcfParameter(Description = "Book to be created, the id will be replaced")] Book value);
```

**Comment by abelsilva** [comment]
why is it expected to have the method name in the URL?

**Comment by colbroth** [comment]
Say for example, if you remove UriTemplate from CreateBooks and CreateAuthor. The swagger view will not show the correct URL to invoke these operations. For this case, the URL should be /v1/rest/CreateBook and /v1/rest/CreateAuthor. Notice how CreateBook is missing and CreateAuthor URL is /v1/rest. When the UriTemplate is not included with WebInvoke, the URL must use the method name.

See photo:
![swagger](https://user-images.githubusercontent.com/12661349/30820281-753884b2-a1ef-11e7-9a30-5f523a5f4c88.png)

**Comment by abelsilva** [comment]
check latest release, let me know if you still have any issues

**Comment by colbroth** [comment]
Release 0.1.28 fixes this issue. Thank you.
