### ISSUE TITLE
With basicauth I got an error "instance failed to match exactly one schema"

### ISSUE THREAD

**Issue by JFDionne** [abelsilva/swaggerwcf#97]
Hi, I'm trying to "play" with your "new" stuff about basic, really cool, but I got an error from the validator.

> {"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"oneOf","message":"instance failed to match exactly one schema (matched 0 out of 6)","schema":{"loadingURI":"http://swagger.io/v2/schema.json#","pointer":"/definitions/securityDefinitions/additionalProperties"},"instance":{"pointer":"/securityDefinitions/basicauth"}}]}

I have this code on Application_Start:
```
        Dim info = New Info() With {
            .Description = "Projet",
            .Version = "1.0.0",
            .Title = "Webservice"
        }

        Dim security = New SecurityDefinitions() From {
            {"basicauth", New SecurityAuthorization() With {
                .Type = "basic",
                .Name = "basicauth"
            }}
        }

        SwaggerWcfEndpoint.Configure(info, security)
```

I'm not sure if it's a bug or something I don't do correctly. Or it's because I use VB?

**Comment by nshrivastava79** [comment]
Comment out the name property. I had same issue which I mentioned in this post

https://github.com/abelsilva/swaggerwcf/issues/93

**Comment by JFDionne** [comment]
Seem to work thank you !

**Comment by abelsilva** [comment]
closing, reopen if you still have any issues
